### ISSUE TITLE
Missing examples for this commandlet?

### ISSUE THREAD

**Issue by Brachus12** [MicrosoftDocs/sccm-docs-powershell-ref#10]
No examples for this commandlet yet?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c144e2d5-cfaf-64f9-979f-4cb1dddf28cf
* Version Independent ID: a462ec18-961f-38e1-11b6-c71d8024421f
* Content: [New-CMDetectionClauseRegistryKeyValue (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmdetectionclauseregistrykeyvalue?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMDetectionClauseRegistryKeyValue.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMDetectionClauseRegistryKeyValue.md)

**Comment by AlBrough** [comment]
New-CMDetectionClauseRegistryKeyValue -ExpectedValue '16.0.10730.20304' -ExpressionOperator GreaterEquals -Hive LocalMachine -KeyName 'Software\Microsoft\Office\ClickToRun\Configuration' -PropertyType Version -Value -ValueName 'VersionToReport'

**Comment by aczechowski** [comment]
Thanks @Brachus12 for the feedback, and thank you @AlBrough for sharing an example! I revised this article to add several examples, including Al's, and update the descriptions on the parameters. This issue will auto-close when my change merges, and then will go live with the next daily publishing cycle (every business day at about 4 PM Pacific time).
