### ISSUE TITLE
How to set Never fallback is not documented

### ISSUE THREAD

**Issue by barthk** [MicrosoftDocs/sccm-docs-powershell-ref#102]
some experimentation shows minus 1 (-1) ticks "Never Fallback", an example:

New-CMBoundaryGroupRelationship -SourceGroupName "Swindon" -DestinationGroupName "London" -FallbackDPMinutes 5 -FallbackSupMinutes -1 -FallbackMPMinutes -1	

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 95198ae5-3151-1955-bcbe-759d6760a644
* Version Independent ID: 785802ab-6dc2-9bf9-e5df-7d723ce426a3
* Content: [New-CMBoundaryGroupRelationship - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmboundarygrouprelationship?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/New-CMBoundaryGroupRelationship.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMBoundaryGroupRelationship.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @barthk for the feedback. I added this to the article, plus a general review and update. I used your example. I also updated the companion articles for Get, Set, & Remove.

The issue will automatically close when my changes merge. The changes will publish live within one day of it merging.
