### ISSUE TITLE
InputObject is what?

### ISSUE THREAD

**Issue by arowswell** [MicrosoftDocs/sccm-docs-powershell-ref#103]
The whole docs site for SCCM PowerShell is completely inadequate and needs significant updates for every single cmdlet. Specifically this cmdlet says it has an InputObject of an IResultObject but doesn't say where that IResultObject comes from. Are we supposed to shake the magic 8 ball and guess? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 26863c9c-e91d-9868-7c27-2431299e6e60
* Version Independent ID: babd14ad-afd6-8d58-ae9a-d151f02b49c9
* Content: [Get-CMDeploymentStatusDetails - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdeploymentstatusdetails?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDeploymentStatusDetails.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDeploymentStatusDetails.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by curtis-compusult** [comment]
You probably figured this out ages ago, but for anyone wondering the same thing, the InputObject required is a CMDeploymentStatus object.

Use it like this:

$status = Get-CMDeploymentStatus -Name "TS Name"
Get-CMDeploymentStatusDetails -InputObject $status

**Comment by aczechowski** [comment]
@arowswell: the Microsoft Open Source Code of Conduct, which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct.

The PowerShell docs are auto-generated from the ConfigMgr module. What's currently published is out of date. I have a pending update to bring it up to the latest version. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs).

Thanks @curtis-compusult for the suggestion.

**Comment by aczechowski** [comment]
I made changes to this article:
- added a description for the **InputObject** parameter
- added an example based on Curtis' suggestion
- added related links
Get-CMDeploymentStatus is an alias, Get-CMPackageDeploymentStatus is the proper cmdlet. Then depending upon what it returns, you may need to specify an array member, e.g., `$status[1]`
These changes will publish live soon with the 2006 content release.
