### ISSUE TITLE
DetectionClauseConnector

### ISSUE THREAD

**Issue by NathanTheGr8** [MicrosoftDocs/sccm-docs-powershell-ref#105]
This page and several other cmdlet pages don't mention the new parameters DetectionClauseConnector and GroupDetectionClauses.

https://docs.microsoft.com/en-us/powershell/sccm/1810-release-notes?view=sccm-ps
Supported cmdlets for Add and Set-CM*DeploymentType have added parameters for GroupDetectionClauses and DetectionClauseConnector.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c6548ba0-8146-8b3d-c7fe-5e6f2e2ed946
* Version Independent ID: 6c5a9d23-8912-14e1-1e3a-9eef7fcd13c9
* Content: [Add-CMScriptDeploymentType - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmscriptdeploymenttype?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMScriptDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMScriptDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mumian
* Microsoft Alias: **jgao**

**Comment by aczechowski** [comment]
Thanks @NathanTheGr8 for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
