### ISSUE TITLE
Missing Parameter for -EnableLEDBAT

### ISSUE THREAD

**Issue by AbfSailor** [MicrosoftDocs/sccm-docs-powershell-ref#108]
The change is listed right here. 
https://docs.microsoft.com/en-us/powershell/sccm/1810-release-notes?view=sccm-ps
Thanks!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65b57301-88d5-bd35-aeb3-f1722a896298
* Version Independent ID: 1c2a0d53-b4d4-961f-067a-b5e71a15ffc5
* Content: [Set-CMDistributionPoint - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmdistributionpoint?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMDistributionPoint.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMDistributionPoint.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AbfSailor for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
