### ISSUE TITLE
Get multiple boundary groups that are specified by name is not possible

### ISSUE THREAD

**Issue by surferstylee** [MicrosoftDocs/sccm-docs-powershell-ref#11]
I am not sure if something has changed with the cmdlet but it is not possible to select multiple Boundary groups in the manner provided by Example 2: PS C:\&gt; Get-CMBoundaryGroup -Name "BGroup01", "BGroup02", "BGroup03"

REAL WORLD:
PS CM1:\&gt; Get-CMBoundaryGroup -Name "Boundary01", "Test01"
Get-CMBoundaryGroup : Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Name'. Specified method is not supported.
At line:1 char:27
+ Get-CMBoundaryGroup -Name "Boundary01", "Test01"
+                           ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-CMBoundaryGroup], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgument,Microsoft.ConfigurationManagement.Cmdlets.HS.Commands.GetBoundaryGroupCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 235c95bb-6b90-8787-afd4-503be7894b9a
* Version Independent ID: 6bbd30e5-ef87-6795-64cc-76461ebab21b
* Content: [Get-CMBoundaryGroup (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmboundarygroup?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMBoundaryGroup.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMBoundaryGroup.md)

**Comment by FISHMANPET** [comment]
claiming for MMS2019 docathon

**Comment by aczechowski** [comment]
This issue is closed because @FISHMANPET contributed the fix. It should be live tomorrow.
