### ISSUE TITLE
Examples Mismatch

### ISSUE THREAD

**Issue by bewshy** [MicrosoftDocs/sccm-docs-powershell-ref#110]
The description for example 1 and 2 refer to "TestDepRule01" and "TestDepRule02" while the example code uses "test" in both examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ebac21df-8b88-b6ac-6100-3de9d3326072
* Version Independent ID: f9d65c87-cf4e-ff42-5bbc-816bc8794505
* Content: [New-CMAutoDeploymentRuleDeployment - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmautodeploymentruledeployment?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/New-CMAutoDeploymentRuleDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMAutoDeploymentRuleDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @bewshy for catching that. I fixed that and cleaned up a few other things. The changes will publish live soon with the 2006 content release.
