### ISSUE TITLE
The example is empty. No clear what this cmdlet use as input.

### ISSUE THREAD

**Issue by Synoptic2** [MicrosoftDocs/sccm-docs-powershell-ref#113]
The example is empty. No clear what this cmdlet use as input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: faf867f1-6517-bd9e-bde0-f55629e10d22
* Version Independent ID: 9d055735-7ea1-a1d4-db48-a64fc01b91f0
* Content: [Get-CMApplicationDeploymentStatus - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmapplicationdeploymentstatus?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMApplicationDeploymentStatus.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMApplicationDeploymentStatus.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Synoptic2, yep, a known issue throughout this content set. The automated tool we use to generate the content leaves those placeholders. I'm working to fill in some of it, but we honestly don't have the resources to address all of it right away. Community contributions to this repo are currently on hold while I fix some problems. Once that's done, then I'm hoping the community can help fill in some of these gaps. So for now, I'm closing this issue.
