### ISSUE TITLE
Poor description for -AccountName parameter

### ISSUE THREAD

**Issue by merlinfrombelgium** [MicrosoftDocs/sccm-docs-powershell-ref#115]
The current description suggests that the site server itself needs an account assigned to it. The parameter name itself does not reflect that it sets the site system installation account. Since renaming the parameter would require change to the code, it may be sufficient to adapt the description.

I suggest the following wording:
_Specifies the account used as Site System Installation Account, other than the site server’s computer account._

Optionally, it could then reference the parameter -UseSiteServerAccount and the [documentation](https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/accounts#site-system-installation-account) for the Site System Installation account. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8fc65ab5-8ee1-2034-12bd-4f82eead9ca0
* Version Independent ID: 68d6d3f0-ae93-7683-53ca-287da395f319
* Content: [Set-CMSiteSystemServer - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmsitesystemserver?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMSiteSystemServer.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMSiteSystemServer.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @merlinfrombelgium for the feedback. I'll revise and do a general cleanup on this and related articles.
