### ISSUE TITLE
InputObject and ObjectId poorly defined

### ISSUE THREAD

**Issue by AlBrough** [MicrosoftDocs/sccm-docs-powershell-ref#12]
Can better description of InputObject and ObjectId be defined with some more working examples.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 015c02b6-5b69-fb85-7cb8-0df13542d71c
* Version Independent ID: fe4333a1-cf0c-c0c0-4960-eed571a06fd3
* Content: [Move-CMObject (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/move-cmobject?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Move-CMObject.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Move-CMObject.md)

**Comment by aczechowski** [comment]
Thanks @AlBrough for the feedback. I revised this article with more detail, explanation, and some better examples. I included a list of object types that I was able to verify work, but I don't think it's complete. I'm checking with engineering to get the full list. But I'll publish what I have so far. This issue will auto-close when my changes merge. It will then go live with the next daily publishing cycle (every business day about 4 PM Pacific time).
