### ISSUE TITLE
-DisableContentDependencyDetection

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#122]
-DisableContentDependencyDetection does not have a description of what it does.  All other switches tell you its behavior, just not this one.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d2f51-0fc4-36da-0ff6-2f4e686da6b8
* Version Independent ID: 4d84de88-c919-ec8e-0037-e483c033898a
* Content: [Remove-CMContentDistribution - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmcontentdistribution?view=sccm-ps#-disablecontentdependencydetection)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMContentDistribution.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMContentDistribution.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for the feedback. I fixed this parameter as well as did a full review/revision of the article and related articles.
