### ISSUE TITLE
Remove-CMContentDistribution (Dependencys)

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#123]
The PS command 'Remove-CMContentDistribution' does not say that it will but it also removes the content for the dependency, at least when use the -Application switch.  This is not the behavior that I was expecting as I would have expected ONLY the content of the application piped in would have been removed.  Not the content of the application and the content of the dependency to the application AND the content to the dependency of the dependency AND etc. etc. etc.

Is there a command the will just remove content for the application piped in?  I thought -DisableContentDependencyDetection might be what I want but there is no description for what it does.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 667d2f51-0fc4-36da-0ff6-2f4e686da6b8
* Version Independent ID: 4d84de88-c919-ec8e-0037-e483c033898a
* Content: [Remove-CMContentDistribution - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmcontentdistribution?view=sccm-ps#-disablecontentdependencydetection)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMContentDistribution.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMContentDistribution.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
I just updated this article along with changes from #122, my understanding is that the parameter **DisableContentDependencyDetection** should do as you describe. If that's not a case, then I suspect that's a product bug. If so, file a frown from the console. https://docs.microsoft.com/powershell/sccm/overview#feedback-for-powershell
