### ISSUE TITLE
Get-CMPackage doesn't return all packages.

### ISSUE THREAD

**Issue by Daren9m** [MicrosoftDocs/sccm-docs-powershell-ref#125]
This document doesn't describe the behavior of the cmdlet. This cmdlet only returns "ordinary packages", not all packages. The causes issues when attempting to identify packages from ID only. It would be helpful to explain the behavior Ray Jia outlines here:

https://social.technet.microsoft.com/Forums/en-US/64fe70aa-3ada-48af-a135-04987435e05d/getcmpackage-missing-packages?forum=ConfigMgrPowerShell

> Note that "get-cmpackages" only get ordinary packages which means what we could see under the tab "\Software Library\Overview\Application Management\Packages", while your SQL query could return all types of packages, and under Content Status we also could see all types of packages except Task Sequence Packages.

The smsprov.log shows the package info when I run get-cmpackage on a software update package, but it is not delivered to the PS console. This is very odd since the info is being successfully queried, but they are not returned???

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee8cbc6-02f1-cf6e-99a6-bbd4764a4822
* Version Independent ID: 3d394c71-412a-9612-36ca-af84f6e37244
* Content: [Get-CMPackage - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmpackage?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMPackage.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMPackage.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Daren9m for the feedback. Get-CMPackage just gets legacy packages that you'll find under the **Application Management** node. Technically, we refer to other objects as packages, but you have to use other cmdlets for them, for example:
- Get-CMDriverPackage]
- Get-CMSoftwareUpdateDeploymentPackage
- Get-CMTaskSequence

I added a note to help clarify, and added these to the related links section. The changes will publish live soon with the 2006 content release.
