### ISSUE TITLE
Add link to Remove-CMSiteRole 

### ISSUE THREAD

**Issue by Skatterbrainz** [MicrosoftDocs/sccm-docs-powershell-ref#127]
[Enter feedback here]

Under associated links, please add Remove-CMSiteRole

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: b993e4f6-b9f2-7004-1738-dd2cafe403fe
* Version Independent ID: 61f6af24-9311-aa4a-bd16-630c942d5b86
* Content: [Get-CMSiteRole - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmsiterole?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMSiteRole.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMSiteRole.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Skatterbrainz for the suggestion. I added this as well as made some other improvements to the article (like a few examples). The changes will publish live soon with the 2006 content release.
