### ISSUE TITLE
article outdated

### ISSUE THREAD

**Issue by EckeD** [MicrosoftDocs/sccm-docs-powershell-ref#128]
This article is outdated, as it is missing information.
The "-fast" switch is not listed and explained.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4ee8cbc6-02f1-cf6e-99a6-bbd4764a4822
* Version Independent ID: 3d394c71-412a-9612-36ca-af84f6e37244
* Content: [Get-CMPackage - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmpackage?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMPackage.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMPackage.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @EckeD for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
