### ISSUE TITLE
Documentation is in complete. Examples and descriptions are missing.

### ISSUE THREAD

**Issue by Reittier** [MicrosoftDocs/sccm-docs-powershell-ref#13]
See subject. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5f20a9-fac3-eea4-6974-b006632f6547
* Version Independent ID: f91bcec0-a21c-b8a7-d139-98dc02032f96
* Content: [New-CMDetectionClauseWindowsInstaller (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmdetectionclausewindowsinstaller?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/New-CMDetectionClauseWindowsInstaller.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMDetectionClauseWindowsInstaller.md)

**Comment by aczechowski** [comment]
Hi @Reittier - yep, a known issue throughout this content set. The automated tool we use to generate the content leaves those placeholders. I'm working to fill in some of it, but we honestly don't have the resources to address all of it right away. Community contributions to this repo are currently on hold while I fix some problems. Once that's done, then I'm hoping the community can help fill in some of these gaps. So for now, I'm closing this issue.
