### ISSUE TITLE
wrong Example 1

### ISSUE THREAD

**Issue by lumirjasny** [MicrosoftDocs/sccm-docs-powershell-ref#132]
The [Example 1](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmdeploymenttypesupersedence?view=sccm-ps#example-1) doesnot work, because no parameter accept pipeline input.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b09651a-71cf-0cc7-e38d-495a99160de3
* Version Independent ID: 69d3047f-05b1-b3c9-950a-4e33495547fe
* Content: [Add-CMDeploymentTypeSupersedence - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmdeploymenttypesupersedence?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMDeploymentTypeSupersedence.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMDeploymentTypeSupersedence.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mumian
* Microsoft Alias: **jgao**

**Comment by aczechowski** [comment]
Thanks @lumirjasny for the feedback. I revised the example and made a few other changes, which will publish live soon with the 2006 content release.
