### ISSUE TITLE
No Examples

### ISSUE THREAD

**Issue by ColinJK** [MicrosoftDocs/sccm-docs-powershell-ref#134]
No Examples, needs more information.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4e39662f-5fe7-5780-b7e4-1ea46c14e011
* Version Independent ID: c6e045b8-f4ec-2b09-5b4d-17ff405facca
* Content: [Get-CMSoftwareUpdateDeployment - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmsoftwareupdatedeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMSoftwareUpdateDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMSoftwareUpdateDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ColinJK, yep, a known issue throughout this content set. The automated tool we use to generate the content leaves those placeholders. I'm working to fill in some of it, but we honestly don't have the resources to address all of it right away. Community contributions to this repo are currently on hold while I fix some problems. Once that's done, then I'm hoping the community can help fill in some of these gaps. So for now, I'm closing this issue.
