### ISSUE TITLE
Hardware Inventory + Class new cmdlets update

### ISSUE THREAD

**Issue by jemmail** [MicrosoftDocs/sccm-docs-powershell-ref#138]
Not documented 

[https://configurationmanager.uservoice.com/forums/300492-ideas/suggestions/12896133-set-cmclientsetting-hardware-inventory](url)

"We have added some new cmdlets for inventory class management: Get-CMInventoryClass, and New-CMInventoryReportClass and Set-CMClientSettingHardwareInventory has new parameters AddInventoryReportClass, CleanInventoryReportClass, and RemoveInventoryReportClass to manage these settings."

**Comment by aczechowski** [comment]
Thanks @jemmail for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
