### ISSUE TITLE
ResourceID and Resource is missing that they accept array's and parameter set is also wrong

### ISSUE THREAD

**Issue by ViperTG** [MicrosoftDocs/sccm-docs-powershell-ref#139]
Both ResourceID and Resource parameter accepts arrays, at least in 1906 and this documentation should reflect that.

ResourceID is int[]
Resource is IResultObject[]

From 1906
```
SYNTAX
    Add-CMDeviceCollectionDirectMembershipRule -CollectionId <string> -ResourceId <int[]> [-PassThru] [-DisableWildcardHandling] [-ForceWildcardHandling] [-WhatIf] [-Confirm]
    [<CommonParameters>]

    Add-CMDeviceCollectionDirectMembershipRule -CollectionId <string> -Resource <IResultObject[]> [-PassThru] [-DisableWildcardHandling] [-ForceWildcardHandling] [-WhatIf]
    [-Confirm]  [<CommonParameters>]

    Add-CMDeviceCollectionDirectMembershipRule -CollectionName <string> -ResourceId <int[]> [-PassThru] [-DisableWildcardHandling] [-ForceWildcardHandling] [-WhatIf] [-Confirm]
    [<CommonParameters>]

    Add-CMDeviceCollectionDirectMembershipRule -CollectionName <string> -Resource <IResultObject[]> [-PassThru] [-DisableWildcardHandling] [-ForceWildcardHandling] [-WhatIf]
    [-Confirm]  [<CommonParameters>]

    Add-CMDeviceCollectionDirectMembershipRule -InputObject <IResultObject#SMS_Collection> -ResourceId <int[]> [-PassThru] [-DisableWildcardHandling] [-ForceWildcardHandling]
    [-WhatIf] [-Confirm]  [<CommonParameters>]

    Add-CMDeviceCollectionDirectMembershipRule -InputObject <IResultObject#SMS_Collection> -Resource <IResultObject[]> [-PassThru] [-DisableWildcardHandling]
    [-ForceWildcardHandling] [-WhatIf] [-Confirm]  [<CommonParameters>]
```
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e4fec0f1-41de-649b-c314-9ff73a8a40c5
* Version Independent ID: 600d116d-6403-9621-ded8-0a37753e5ea8
* Content: [Add-CMDeviceCollectionDirectMembershipRule - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmdevicecollectiondirectmembershiprule?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMDeviceCollectionDirectMembershipRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMDeviceCollectionDirectMembershipRule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ViperTG, this content is auto generated based on what's in the module. I have an update pending to bring it all up to date with the latest version.
