### ISSUE TITLE
Missing Product reference for cmdlets

### ISSUE THREAD

**Issue by MSBeatriz** [MicrosoftDocs/sccm-docs-powershell-ref#14]
This article is missing some description about cmdlet usage (example is blank) nd would be useful to have reference of versions where it applies and not apply.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 593be7ad-071e-10ca-547f-7bcd49f4ea58
* Version Independent ID: c5e7c2a0-98cc-7e1b-d8bf-d75134904cd1
* Content: [Set-CMTSStepRunCommandLine (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmtsstepruncommandline?view=sccm-ps#examples)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMTSStepRunCommandLine.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMTSStepRunCommandLine.md)

**Comment by aczechowski** [comment]
Thanks @MSBeatriz for the feedback. This content is mostly auto generated from what's in the module. What's currently published is as of version 1902. I have a pending update to bring it up to the latest version, and then a new process to keep it up to date going forward.

The cmdlet should apply to all supported product versions.

As for example, we have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). We rely on community support to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).
