### ISSUE TITLE
Install-Package failing!

### ISSUE THREAD

**Issue by felymich** [MicrosoftDocs/sccm-docs-powershell-ref#140]
Hello,

I am trying to install NuGet to use with Powershell for SCCM...
Installation Nuget Package provider

Install-PackageProvider -Name NuGet -RequiredVersion 2.8.5.201 -Force

In order to execute the first time, PackageManagement requires an internet connection to download the Nuget package provider. However, if your computer does not have an internet connection and you need to use the Nuget or PowerShellGet provider, you can download them on another computer and copy them to your target computer. Use the following steps to do this:
------------------------------------------------------------------------------------------------------------
Run Install-PackageProvider -Name NuGet -RequiredVersion 2.8.5.201 -Force to install the provider from a computer with an internet connection.
After the install, you can find the provider installed in $env:ProgramFiles\PackageManagement\ReferenceAssemblies\\\\ or $env:LOCALAPPDATA\PackageManagement\ProviderAssemblies\\\\.
Place the folder, which in this case is the Nuget folder, in the corresponding location on your target computer. If your target computer is a Nano server, you need to run Install-PackageProvider from Nano Server to download the correct Nuget binaries.
Restart PowerShell to auto-load the package provider. Alternatively, run Get-PackageProvider -ListAvailable to list all the package providers available on the computer. Then use Import-PackageProvider -Name NuGet -RequiredVersion 2.8.5.201 to import the provider to the current Windows PowerShell session.
--------------------------------------------------------------------------------------------------------------
PS C:\Windows\system32> Install-PackageProvider -Name NuGet -RequiredVersion 2.8.5.201 -Force 
Name                           Version          Source             Summary                                                  
----                                -------          ------                 -------                                                     
nuget                          2.8.5.201        https://onege... NuGet provider for the OneGet meta-package manager                                             
Register-P
------------------------------------------------------------------------------------------------------------
PS E:\sources> Get-PackageProvider -ListAvailable
Name                     Version          DynamicOptions                                                                                                        
----                     -------          --------------                                                                                                        
msi                      3.0.0.0          AdditionalArguments                                                                                                   
msu                      3.0.0.0                                                                                                                                
NuGet                    2.8.5.208        Destination, ExcludeVersion, Scope, SkipDependencies, Headers, FilterOnTag, Contains, AllowPrereleaseVersions, Conf...
PowerShellGet            1.0.0.1          PackageManagementProvider, Type, Scope, AllowClobber, SkipPublisherCheck, InstallUpdate, NoPathUpdate, Filter, Tag,...
--------------------------------------------------------------------------------------------------------------
but when trying to install packages I am getting an error...
--------------------------------------------------------------------------------------------------------------
PS C:\Windows\system32> Install-Package microsoft.aspnet.razor
Install-Package : No match was found for the specified search criteria and package name 'microsoft.aspnet.razor'. Try Get-PackageSource to see all available 
registered package sources.
At line:1 char:1
+ Install-Package microsoft.aspnet.razor
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
--------------------------------------------------------------------------------------------------------------
even I have the package...
--------------------------------------------------------------------------------------------------------------
PS E:\Sources\Powershell> Find-Package ./
Name                           Version          Source           Summary                                                                                        
----                           -------          ------           -------                                                                                        
Microsoft.AspNet.Razor         3.2.7            E:\Sources\Po... This package contains the runtime assemblies for ASP.NET Web Pages.                            
Microsoft.AspNet.WebPages      3.2.7            E:\Sources\Po... This package contains core runtime assemblies shared between ASP.NET MVC and ASP.NET Web Pages.
Microsoft.Web.Infrastructure   1.0.0.0          E:\Sources\Po... This package contains the Microsoft.Web.Infrastructure assembly that lets you dynamically re...
Microsoft.AspNet.Mvc           4.0.40804.0      E:\Sources\Po... This package contains the runtime assemblies for ASP.NET MVC. ASP.NET MVC gives you a powerf...
--------------------------------------------------------------------------------------------------------------
or...
--------------------------------------------------------------------------------------------------------------
PS C:\Windows\system32> Get-PackageSource
Name                             ProviderName     IsTrusted  Location                                                                                           
----                             ------------     ---------  --------                                                                                           
nuget.org                        NuGet            False      https://api.nuget.org/v3/index.json                                                                
PsRepository                     PowerShellGet    True       E:\Sources\Powershell                                                                              
--------------------------------------------------------------------------------------------------------------
Not sure why it refuse to install!!!
--------------------------------------------------------------------------------------------------------------
PS C:\Windows\system32> Get-PackageSource -Location https://api.nuget.org/v3/index.json
Name                             ProviderName     IsTrusted  Location                                                                                           
----                             ------------     ---------  --------                                                                                           
nuget.org                        NuGet            False      https://api.nuget.org/v3/index.json                                                                
--------------------------------------------------------------------------------------------------------------
PS C:\Windows\system32> Get-PackageSource -Location E:\Sources\Powershell
Name                             ProviderName     IsTrusted  Location                                                                                           
----                             ------------     ---------  --------                                                                                           
PsRepository                     PowerShellGet    True       E:\Sources\Powershell         
--------------------------------------------------------------------------------------------------------------

Any idea?
Thanks,
Dom

**Comment by felymich** [comment]
I even tried to register www.nuget.org but it failed!!

PS C:\Windows\system32> Register-PSRepository -Name "NuGet" -SourceLocation "https://www.nuget.org" -PublishLocation "https://www.nuget.org/Packages" -InstallationPolicy Trusted 
Register-PSRepository : The specified Uri 'https://www.nuget.org/' for parameter 'SourceLocation' is an invalid Web Uri. Please ensure that it meets the Web 
Uri requirements.
At line:1 char:1
+ Register-PSRepository -Name "NuGet" -SourceLocation "https://www.nuge ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (https://www.nuget.org/:String) [Register-PSRepository], ArgumentException
    + FullyQualifiedErrorId : InvalidWebUri,Register-PSRepository

**Comment by felymich** [comment]
More information:

PS C:\Users\rmppqx\AppData\Local\Temp> Install-Package -Verbose microsoft.aspnet.razor
VERBOSE: Using the provider 'Programs' for searching packages.
VERBOSE: Using the provider 'NuGet' for searching packages.
VERBOSE: Using the provider 'msi' for searching packages.
VERBOSE: Using the provider 'msu' for searching packages.
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'C:\Users\rmppqx\AppData\Local\Temp' and PackageManagementProvider is 'NuGet'.
VERBOSE: An error occurred while sending the request.
VERBOSE: Retry downloading 'https://api.nuget.org/v3/index.json' for '2' more times
VERBOSE: Total package yield:'0' for the specified package 'microsoft.aspnet.razor'.
VERBOSE: An error occurred while sending the request.
VERBOSE: Retry downloading 'https://api.nuget.org/v3/index.json' for '1' more times
VERBOSE: An error occurred while sending the request.
VERBOSE: Retry downloading 'https://api.nuget.org/v3/index.json' for '0' more times
VERBOSE: Total package yield:'0' for the specified package 'microsoft.aspnet.razor'.
Install-Package : No match was found for the specified search criteria and package name 'microsoft.aspnet.razor'. Try Get-PackageSource to see all available 
registered package sources.
At line:1 char:1
+ Install-Package -Verbose microsoft.aspnet.razor
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by aczechowski** [comment]
Thanks @felymich for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
