### ISSUE TITLE
DeployWithoutLicense True/False around the wrong way.

### ISSUE THREAD

**Issue by IJustKnowStuff** [MicrosoftDocs/sccm-docs-powershell-ref#141]
The description for "DeployWithoutLicense" has $TRUE and $FALSE around the wrong way.
It's correct in the description for the "set-cmsoftwareupdateautodeploymentrule" command.
I've also tested this on a Windows 2016 Server with Config Manager 1910.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a909f32d-5808-1dfc-f835-95fb8b260c54
* Version Independent ID: 9b1587a0-72ba-a5c6-3404-ac26b0797ed9
* Content: [New-CMSoftwareUpdateAutoDeploymentRule - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmsoftwareupdateautodeploymentrule?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMSoftwareUpdateAutoDeploymentRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMSoftwareUpdateAutoDeploymentRule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @IJustKnowStuff for catching that. I made a change to the article, which will publish live soon with the 2006 content release.
