### ISSUE TITLE
Get-CMManagementPointComponent has been deprecated

### ISSUE THREAD

**Issue by PrajwalDesai** [MicrosoftDocs/sccm-docs-powershell-ref#145]
When you use this cmdlet you see the below warning. I think this must be added as a note to the article.

The WARNING: The cmdlet 'Get-CMManagementPointComponent' has been deprecated and may be removed in a future release. The cmdlet 'Get-CMSiteDefinition' may be used as a replacement.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d205bfd1-0f54-8394-2fc7-612e55c2b350
* Version Independent ID: 8010c1f6-b62f-5d9e-ae03-bc85d013f3e1
* Content: [Get-CMManagementPointComponent (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmmanagementpointcomponent?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMManagementPointComponent.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMManagementPointComponent.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PrajwalDesai, this content is auto generated based on what's in the module. I have an update pending to bring the content up to date with the latest version of the module. If that doesn't address this feedback, then I suggest that you file [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback). There hasn't been anything noted about this in release notes (which is generated by the engineering team).
