### ISSUE TITLE
Document available action types

### ISSUE THREAD

**Issue by Yupiter2005** [MicrosoftDocs/sccm-docs-powershell-ref#147]
Now it's only RequestMachinePolicyNow.

Available actions are public in ConfigMgr DB: select * from clientactiontype

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8723bff-f2e7-1ead-7349-315b5d6c0f3b
* Version Independent ID: c82275d1-dcd4-4be1-8031-dd91f38b53a7
* Content: [Invoke-CMClientNotification (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/invoke-cmclientnotification?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Invoke-CMClientNotification.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Invoke-CMClientNotification.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Yupiter2005 - I have some updates pending to bring this content up to date with the latest module version. We auto generate these docs based on what's in the module. So if it's not in the module, it won't be in the docs. I'm closing this request. If you feedback on the cmdlet itself, please file [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/find-help#product-feedback).
