### ISSUE TITLE
"Configuration Manager cmdlet reference" Link Broken

### ISSUE THREAD

**Issue by jholl016** [MicrosoftDocs/sccm-docs-powershell-ref#148]
Link target is: https://docs.microsoft.com/en-us/powershell/module/configurationmanager/configurationmanager?view=sccm-ps which produces 404 Content Not Found.

Link target should be: https://docs.microsoft.com/en-us/powershell/module/configurationmanager/?view=sccm-ps

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3cfeb8-c773-1ae5-0975-ea48e20e4c3a
* Version Independent ID: 7794c3e5-20ad-e389-6e18-c70628a3505a
* Content: [Get started with ConfigMgr cmdlets - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/overview?view=sccm-ps)
* Content Source: [docs-conceptual/overview.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jholl016 for the feedback. We made some changes to the repo that should fix this issue more permanently. 🤞 I just submitted a change that should publish live tomorrow.
