### ISSUE TITLE
File extension incorrect

### ISSUE THREAD

**Issue by Mhudson97** [MicrosoftDocs/sccm-docs-powershell-ref#149]
Query.xml should be Query.MOF, this is the same for the import-CMQuery command.

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1aa292a1-010f-a79d-60eb-07b6ed5600e9
* Version Independent ID: ef85fd05-6037-13f3-2ea7-5e1d4957d6ba
* Content: [Export-CMQuery (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/ConfigurationManager/Export-CMQuery?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Export-CMQuery.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Export-CMQuery.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Mhudson97 for catching that. I corrected both articles. The changes will publish live soon with the 2006 content release.
