### ISSUE TITLE
update-cmthirdpartyupdate

### ISSUE THREAD

**Issue by rdoloto-nps** [MicrosoftDocs/sccm-docs-powershell-ref#150]
This is  just are request and i will submit user voice for this item. It would be great to have update-cmthirdparty -sync  option  in the future releases . This  is to just sync  catalog with cmdlet

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5a071f8a-53b4-af3f-16ae-fa25a81282c3
* Version Independent ID: fc04bcd7-8372-689c-f464-14f81ab34dd8
* Content: [Version 1910 release notes - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/1910-release-notes?view=sccm-ps#feedback)
* Content Source: [docs-conceptual/1910-release-notes.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/1910-release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @rdoloto-nps, as it's product feedback, I'm closing this doc issue, nothing actionable for docs at this time until a cmdlet is added  to the module. 😄
