### ISSUE TITLE
Missing information

### ISSUE THREAD

**Issue by n-athan** [MicrosoftDocs/sccm-docs-powershell-ref#153]
The Synopsis, Description and Examples are not yet filled in on this page, or in the help documentation in Powershell. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eeaeda7-0d77-1867-4660-2f5e0af4cd5a
* Version Independent ID: 0cd8f378-f1b3-f4a9-412a-2ca5e2b43dee
* Content: [Invoke-CMClientAction (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/invoke-cmclientaction?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Invoke-CMClientAction.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Invoke-CMClientAction.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @n-athan, yep, a known issue throughout this content set. The automated tool we use to generate the content leaves those placeholders. I'm working to fill in some of it, but we honestly don't have the resources to address all of it right away. Community contributions to this repo are currently on hold while I fix some problems. Once that's done, then I'm hoping the community can help fill in some of these gaps. So for now, I'm closing this issue.
