### ISSUE TITLE
Example is only a cmd prompt

### ISSUE THREAD

**Issue by N5ZY** [MicrosoftDocs/sccm-docs-powershell-ref#156]
The example is merely a command prompt, not an actual example of this cmdlet.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18696f54-bc1e-9216-1dcb-5eb8ff24278d
* Version Independent ID: ca716a63-5604-be52-af85-30c84f3545ae
* Content: [Get-CMDistributionStatus (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdistributionstatus?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDistributionStatus.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDistributionStatus.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
The PowerShell docs are auto-generated from the ConfigMgr module. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). We rely on community support from members like you to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).

**Comment by aczechowski** [comment]
Thanks to @baardhermansen for submitting an edit to the article to add this example! It should go live with daily publishing later this afternoon (Pacific).
