### ISSUE TITLE
Missing content

### ISSUE THREAD

**Issue by NeverEnoughCoffeeMan** [MicrosoftDocs/sccm-docs-powershell-ref#157]
These four parameters lack descriptions; they appear to be marked as TO-DO items:

-DetectionClauseConnector
{{ Fill DetectionClauseConnector Description }}

-GroupDetectionClauses
{{ Fill GroupDetectionClauses Description }}

-UninstallContentLocation
{{ Fill UninstallContentLocation Description }}

-UninstallOption
{{ Fill UninstallOption Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec6f7db-a33c-ea9a-90d6-31261e8e28e2
* Version Independent ID: 4ecd32f7-c8e7-a810-728c-9ad1c659af2a
* Content: [Add-CMMsiDeploymentType (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmmsideploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMMsiDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMMsiDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @NeverEnoughCoffeeMan, yep, a known issue throughout this content set. The automated tool we use to generate the content leaves those placeholders. I'm working to fill in some of it, but we honestly don't have the resources to address all of it right away. Community contributions to this repo are currently on hold while I fix some problems. Once that's done, then I'm hoping the community can help fill in some of these gaps. So for now, I'm closing this issue.
