### ISSUE TITLE
-AddRequirement

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#158]
Can you add an example for how to use "-AddRequirement" with Set-CMScriptDeploymentType.  I don't understand how to input the 'rule'.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5bf05db7-2746-34c9-9111-740b8cc6b3b3
* Version Independent ID: 63bc0201-1719-bfae-eecb-719e895d1192
* Content: [Set-CMScriptDeploymentType (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmscriptdeploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMScriptDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMScriptDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Barleyologist, I found an example in the [1810 release notes](https://docs.microsoft.com/powershell/sccm/1810-release-notes#add-a-language-rule) that I'll pull into this article, as well as make some revisions so the cmdlet and parameter descriptions are more accurate. Thanks for the feedback!

**Comment by aczechowski** [comment]
This turned into a larger change, but once published, it _should_ make this easier to understand. I ended up updating most of the DT cmdlet articles, the several articles for detection methods, and all of the requirement rule cmdlet articles. I hope to get this published soon. Let me know if you have specific questions, I now understand how this all works! (And I want to also add some more conceptual content to the core docs on how to put all of this together. But save that for another day.)
