### ISSUE TITLE
Example is incorrect

### ISSUE THREAD

**Issue by phriendx** [MicrosoftDocs/sccm-docs-powershell-ref#159]
The example provided here is broken. There is no such parameter as "DateTime".  It would be good to either remove this example or provide better ones.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f4d670cd-926f-26b3-00b6-176437bd086c
* Version Independent ID: 57df715a-6a85-1362-e5db-9b76ab03df85
* Content: [New-CMSchedule (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmschedule?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/New-CMSchedule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMSchedule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @phriendx for the feedback. I updated the article in general, as well as fixed the examples. The changes will publish live soon with the 2006 release.
