### ISSUE TITLE
Example is incomplete.

### ISSUE THREAD

**Issue by jacorbello** [MicrosoftDocs/sccm-docs-powershell-ref#16]
There is no example for the New-CMDetectionClauseRegistryKey

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e42cf303-ca97-f2ff-5924-89769725b4b2
* Version Independent ID: df7120b0-168f-4d30-bb16-68f85541e422
* Content: [New-CMDetectionClauseRegistryKey (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmdetectionclauseregistrykey?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMDetectionClauseRegistryKey.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMDetectionClauseRegistryKey.md)

**Comment by 1RedOne** [comment]
After looking into this one, I dont' see how this cmdlet could work in the first place.  It doesn't have an input param for a particular app or deployment type.  How would it know on to what to add this new DetectionClause?

**Comment by casimpson1988** [comment]
Firstly you have to create the object using New-CMDetectionClauseRegistryKey. I save this to a variable and then call it when using Add-CMDeploymentType via the -AddDetectionClause parameter.

**Comment by aczechowski** [comment]
We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). We rely on community support to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).
