### ISSUE TITLE
Set-CMMsiDeploymentType –ContentLocation dosent work

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#160]
I can get Set-CMScriptDeploymentType –ContentLocation to work, just not Set-CMMsiDeploymentType –ContentLocation.  I do not believe I am doing anything wrong.  Also there is ZERO error msg, no verbose, no warning... nothing.  Very difficult to figure out what you are doing wrong.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f449bff4-6a65-3023-da68-d2aab5d8fe35
* Version Independent ID: 669d6626-0b51-c441-f5ad-a4c42fbe8d67
* Content: [Set-CMMsiDeploymentType (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmmsideploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMMsiDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMMsiDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
