### ISSUE TITLE
DeploymentOption incorrect default

### ISSUE THREAD

**Issue by CaptainUnlikely** [MicrosoftDocs/sccm-docs-powershell-ref#163]
This page states that the default option for DeploymentOption is DownloadContentLocallyWhenNeededByRunningTaskSequence, however it's actually DownloadAllContentLocallyBeforeStartingTaskSequence.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c866e1-8480-d544-0661-a9058a7df8b9
* Version Independent ID: c1ac5a0e-7fee-ab54-b482-3789a0b008b5
* Content: [New-CMTaskSequenceDeployment (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmtasksequencedeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMTaskSequenceDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMTaskSequenceDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @CaptainUnlikely for the feedback. There were a few issues with this article. I cleaned it up. The changes will publish live soon with the 2006 content release.
