### ISSUE TITLE
Example 1 modification

### ISSUE THREAD

**Issue by NEllis280** [MicrosoftDocs/sccm-docs-powershell-ref#164]
Example 1 shows use of the -SiteSystemServerName parameter, which is not a valid parameter for this commandlet. Recommend removing from the example.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e978a3de-aab2-033e-df51-2c1733adba61
* Version Independent ID: 116cf063-4163-e1c2-e78c-e56ef8528711
* Content: [Set-CMAssetIntelligenceSynchronizationPoint (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmassetintelligencesynchronizationpoint?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMAssetIntelligenceSynchronizationPoint.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMAssetIntelligenceSynchronizationPoint.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @NEllis280 for the feedback. The example was a bit of a mess in general. I replaced it with a more practical example. The change will go live soon with the 2006 content release.

**Comment by NEllis280** [comment]
No worries. I came across it while writing the DSC resource for this
commandlet and figured I would give you a heads up!
