### ISSUE TITLE
Needs new parameters added

### ISSUE THREAD

**Issue by rbreneman** [MicrosoftDocs/sccm-docs-powershell-ref#166]
AS of the 2002 release (maybe earlier), there are parameters for -DriverManufacturer and -DriverModel that are missing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2b20651c-820b-ecff-b2fe-2be9ccdcb286
* Version Independent ID: f18c03cb-e617-81cf-0d67-402e20a31ca6
* Content: [New-CMDriverPackage (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmdriverpackage?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMDriverPackage.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMDriverPackage.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @rbreneman, literally working on that update now. Hope to have it (and many others) published in the next week or so.
