### ISSUE TITLE
Task Sequence 'Disabled'

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#167]
How do I determine if a Task Sequence is disabled?  Get-CMTaskSequence does not seem to pull this information yet oddly there is a field which seems logical but never seem to be populated with any information (TsEnabled).

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 12aa78ed-00aa-5c58-1b43-a497d0e05779
* Version Independent ID: 5ec2f497-164c-5c45-47f1-74ffa3aa93d2
* Content: [Get-CMTaskSequence (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmtasksequence?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMTaskSequence.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMTaskSequence.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Barleyologist - I'm seeing the same thing. I would expect the `TsEnabled` property to have some value, but I tried it against two different task sequences of different states, and both are null. I suggest filing a frown from the console. I did find an existing product bug (internal reference 2840148), where that property doesn't display for WMI. So it's probably a lower-level issue that's just exposed the same through PowerShell. I made a note of this issue in the bug. If you file a frown it might just be closed as a duplicate, but at least lets the engineering team that folks are still asking about it. 😄
