### ISSUE TITLE
New-CMStatusFilterRule example code uses non-existent Parameter "PropertyName"

### ISSUE THREAD

**Issue by hkystar35** [MicrosoftDocs/sccm-docs-powershell-ref#169]
Example code uses parameter `-PropertyName` that does not exist:
```powershell
PS XYZ:\> New-CMStatusFilterRule -SiteCode "Contoso2" -Name "11211" -TargetSiteCode "Contoso2" -Source "SMS Provider" -System "Contoso-test" -Component "1111" -MessageType Milestone -SeverityType Informational -MessageId "1234" -PropertyName "403" -PropertyValue "123" -WriteToDatabase $True -AllowDeleteMessagesTimeDays 20 -ReportToEventLog $False -ReplicateToParentSite $False -RunProgram $False -ForwardToStatusSummarizers $True -ProcessLowerPriorityRules $True
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 38cb6cc5-a5e3-c7d3-4bcc-641da04bd7c0
* Version Independent ID: 53e17807-fd2e-fbc9-2c4e-7b0a226df3fc
* Content: [New-CMStatusFilterRule (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmstatusfilterrule?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMStatusFilterRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMStatusFilterRule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @hkystar35 for catching that. The example unfortunately has a number of issues. I just rewrote it with proper parameter names and a more realistic situation. The change will publish live soon with the 2006 content set.

**Comment by hkystar35** [comment]
Thank you, @aczechowski !
