### ISSUE TITLE
Is this cmdlet actually deprecated?

### ISSUE THREAD

**Issue by RobotScience** [MicrosoftDocs/sccm-docs-powershell-ref#17]
Or is that a typo? There were bug fixes to this cmdlet with 1610 (https://docs.microsoft.com/en-us/powershell/sccm/1610_release_notes?view=sccm-ps) and I'm not finding any suitable replacement cmdlet. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d700e032-eacd-78be-72b7-6d4a0429449d
* Version Independent ID: 4fa54d15-92b5-2cef-f3fb-4cb304ebaece
* Content: [Add-CMDeploymentType - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmdeploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMDeploymentType.md)
* Product: **configuration-manager**
* GitHub Login: @mumian
* Microsoft Alias: **jgao**

**Comment by codaamok** [comment]
I just had it pointed out to me that there are cmdlets per deployment type "type" now. e.g. Add-CMScriptDeploymentType

**Comment by aczechowski** [comment]
Probably worth making a note to reference the other cmdlets

**Comment by aczechowski** [comment]
Oh, I should have noticed this earlier, the list of replacement cmdlets is already in the [Description](https://docs.microsoft.com/powershell/module/configurationmanager/add-cmdeploymenttype?view=sccm-ps#description)

Use one of the following cmdlets:

* [Add-CMAndroidDeploymentType](Add-CMAndroidDeploymentType.md)
* [Add-CMAppv5XDeploymentType](Add-CMAppv5XDeploymentType.md)
* [Add-CMAppvDeploymentType](Add-CMAppvDeploymentType.md)
* [Add-CMGooglePlayDeploymentType](Add-CMGooglePlayDeploymentType.md)
* [Add-CMIosAppStoreDeploymentType](Add-CMIosAppStoreDeploymentType.md)
* [Add-CMIosDeploymentType](Add-CMIosDeploymentType.md)
* [Add-CMMacDeploymentType](Add-CMMacDeploymentType.md)
* [Add-CMMobileMsiDeploymentType](Add-CMMobileMsiDeploymentType.md)
* [Add-CMMsiDeploymentType](Add-CMMsiDeploymentType.md)
* [Add-CMScriptDeploymentType](Add-CMScriptDeploymentType.md)
* [Add-CMWebApplicationDeploymentType](Add-CMWebApplicationDeploymentType.md)
* [Add-CMWindowsAppxDeploymentType](Add-CMWindowsAppxDeploymentType.md)
* [Add-CMWindowsPhoneDeploymentType](Add-CMWindowsPhoneDeploymentType.md)
* [Add-CMWindowsPhoneStoreDeploymentType](Add-CMWindowsPhoneStoreDeploymentType.md)
* [Add-CMWindowsStoreDeploymentType](Add-CMWindowsStoreDeploymentType.md)
