### ISSUE TITLE
Incomplete article

### ISSUE THREAD

**Issue by hwkwicre** [MicrosoftDocs/sccm-docs-powershell-ref#173]
A few {{ Fill Description }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: affd69ed-f705-5019-391c-5a7ff1b8eafd
* Version Independent ID: 4e961607-0ac2-b6de-337d-ccdd89fcf86c
* Content: [Set-CMBoundaryGroup (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmboundarygroup?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMBoundaryGroup.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMBoundaryGroup.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @hwkwicre, yep, a known issue throughout this content set. The automated tool we use to generate the content leaves those placeholders. I'm working to fill in some of it, but we honestly don't have the resources to address all of it right away. Community contributions to this repo are currently on hold while I fix some problems. Once that's done, then I'm hoping the community can help fill in some of these gaps. So for now, I'm closing this issue.
