### ISSUE TITLE
Error in the values for -ClientLogType

### ISSUE THREAD

**Issue by NEllis280** [MicrosoftDocs/sccm-docs-powershell-ref#175]
[Enter feedback here]
Currently:

AllMilestones
AllMilestonesAndAllDetails
AllMilestonesAndAllDetails
ErrorMilestones

What it should be:

AllMilestones
AllMilestonesAndAllDetails
ErrorAndWarningMilestones
ErrorMilestones

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e261c505-d4bc-f8f2-39f0-85989b943c83
* Version Independent ID: 02429294-6327-d7ff-81b7-1c307105ee7e
* Content: [Set-CMStatusReportingComponent (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmstatusreportingcomponent?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMStatusReportingComponent.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMStatusReportingComponent.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @NEllis280 for the feedback. I'll probably just strike the bulleted list of values, since it's redundant with the accurate **Accepted values** row (which is auto-generated from the module, so should always match 😉 )

**Comment by NEllis280** [comment]
Sounds great! Just saw that and figured it might confuse some people.

**Comment by aczechowski** [comment]
I just made a change for this issue. It will publish with the 2006 content release soon.
