### ISSUE TITLE
Pulling wrong (Old) data in 'SDMPackageXML'

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#176]
I have an application that once used a Powershell script to control Detection method and now uses a Registry Entry.  When I use Get-CMApplication it still shows the old Powershell Detection Script in 'SDMPackageXML' data.  I have removed all Revision history information for the app and no change.  The same happens when using 'Get-CMDeploymentType'. I am currently using '.AppMgmtDigest.DeploymentType.Installer.CustomData.DetectionScript.Language' in my script and is giving me a false positive of the detection method for the application I am using.  

I have also tried changing the detection method on the app to PowerShell of a new script, saving, then changing back to Registry method, delete revision history.  This resulted in the 'SDMPackageXML' data showing me the newer PS script which is not accurate as the detection method of the app is no longer a PS script.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d394087a-7a27-3cc2-8ed9-c8cbd43e667e
* Version Independent ID: 8ca6e2a3-67ef-f759-5c20-e218f10a4f20
* Content: [Get-CMApplication (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmapplication?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMApplication.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMApplication.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.

p.s. on the surface it sounds like a lazy properties issue.
