### ISSUE TITLE
No examples?

### ISSUE THREAD

**Issue by curtmgray** [MicrosoftDocs/sccm-docs-powershell-ref#18]
Can we get some examples for this?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e7df9f7-df89-07fa-6c7e-03db5080d76d
* Version Independent ID: 9f3e914b-9e41-7e98-a7f1-f01c31b881ab
* Content: [New-CMSoftwareUpdateDeployment (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmsoftwareupdatedeployment?view=sccm-ps#optional-parameters)
* Content Source: [sccm-ps/ConfigurationManager/New-CMSoftwareUpdateDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMSoftwareUpdateDeployment.md)

**Comment by 1RedOne** [comment]
@aczechowski I claim this one for the #MSDocathon

**Comment by enternoescape** [comment]
This issue was brought up 7 months ago. Are there any plans to have examples for this cmdlet?

**Comment by 1RedOne** [comment]
I unclaim this one

**Comment by aczechowski** [comment]
We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). We rely on community support to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).
