### ISSUE TITLE
Missing ExpressionOperator (NotBeginsWith)

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#180]
Doc does not indicate if -ExpressionOperator accepts (NotBeginsWith).  All other operates are present in the doc.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c144e2d5-cfaf-64f9-979f-4cb1dddf28cf
* Version Independent ID: a462ec18-961f-38e1-11b6-c71d8024421f
* Content: [New-CMDetectionClauseRegistryKeyValue (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmdetectionclauseregistrykeyvalue?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMDetectionClauseRegistryKeyValue.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMDetectionClauseRegistryKeyValue.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @Barleyologist, thanks for the feedback. Those values are auto-populated from the module. So if a value isn't listed, there's either some bug in the module, or it just doesn't support it. Please file a frown from the Configuration Manager console.
