### ISSUE TITLE
Disable-CMTaskSequence

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#184]
Disable-CMTaskSequence is Depricated and should be removed from Related Links

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 188952b9-b36a-d955-32bf-c7a20e7c0166
* Version Independent ID: adc9e119-4e52-440e-83d2-753494a0d4fa
* Content: [Set-CMTaskSequence (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmtasksequence?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMTaskSequence.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMTaskSequence.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist, good feedback. It looks like it's linked from several other articles, the same as **Enable-CMTaskSequence**. I'll remove both of those links, and do a search for other similar cmdlets to cleanup. 😄 This issue will auto-close when my change is merged, which means it will publish live with the next daily publishing process (~4 PM Pacific)
