### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by miguelrodriguezeicke** [MicrosoftDocs/sccm-docs-powershell-ref#186]
One example (using the package ID as a parameter) would be

$PACKAGEID=(Get-CMApplication -Name '*7-Zip*').PackageID 
Get-CMDistributionStatus -Id $PACKAGEID

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93365baa-ff01-7554-9230-1acaf35764ef
* Version Independent ID: ca716a63-5604-be52-af85-30c84f3545ae
* Content: [Get-CMDistributionStatus (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/ConfigurationManager/Get-CMDistributionStatus?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDistributionStatus.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDistributionStatus.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @miguelrodriguezeicke for the feedback! Did you know you can add this yourself? 😉 For more information, see [How to contribute](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs#bkmk_contribute).
If not, that's ok! Either someone from the community will add it, or I'll do it sometime soon.

**Comment by aczechowski** [comment]
Thanks to @baardhermansen for submitting an edit to the article to add this example! It should go live with daily publishing later this afternoon (Pacific).
