### ISSUE TITLE
Documentation Updates

### ISSUE THREAD

**Issue by mikeh36** [MicrosoftDocs/sccm-docs-powershell-ref#19]
Any timeline on when the documentation is going to be updated on for the actual cmdlet examples. For example: Set-CMApplication (https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmapplication?view=sccm-ps) has no mention or examples for the new parameters. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c66ae763-8992-e2d0-97f0-22bfe4af182f
* Version Independent ID: a2848286-bdb8-ffa1-65be-205f795fc559
* Content: [System Center Configuration Manager Cmdlet Library changes for Current Branch 1802](https://docs.microsoft.com/en-us/powershell/sccm/1802_release_notes?view=sccm-ps)
* Content Source: [docs-conceptual/1802_Release_Notes.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/1802_Release_Notes.md)
* GitHub Login: @aczechowski

**Comment by aczechowski** [comment]
Thanks @mikeh36 for the feedback. We unfortunately have a large backlog of work for the PowerShell content, but are looking at ways to improve it in the future.

**Comment by aczechowski** [comment]
This content is mostly auto generated from what's in the module, and what's currently published is as of version 1902. I have a pending update to bring it up to the latest version, and then a new process to keep it up to date going forward. I'm going to close this issue.

As for examples... We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). We rely on community support from members like you to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).
