### ISSUE TITLE
There're no examples given

### ISSUE THREAD

**Issue by MHimken** [MicrosoftDocs/sccm-docs-powershell-ref#193]
Please add some examples to this page or remove the examples section. I assume this was just a copy/paste error. Also, I'd recommend adding two related cmdlets Remove-CMDeviceCollectionDirectMembershipRule and Remove-CMUserCollectionDirectMembershipRule as they do the same, but object-specific. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3d672647-be09-57ad-68fa-787f315bfc65
* Version Independent ID: 5fc975aa-83c2-5da9-e59d-755449a495b5
* Content: [Remove-CMCollectionDirectMembershipRule (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmcollectiondirectmembershiprule?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMCollectionDirectMembershipRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMCollectionDirectMembershipRule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MHimken for the feedback. The PowerShell docs are mostly auto-generated from the ConfigMgr module. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). We rely on community support from members like you to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).

**Comment by AndrzejWojtowicz** [comment]
So is Microsoft relying on community to do the guesswork and submit the docs instead of MS employees these days?  What if community does not provide examples, are we going to be left in the dark? Looks like the data is piling up. If MS was not closed-source model then maybe you could count on community support. Truly intriguing that tech giant like MS who keeps the source behind closed doors and every service is a paid one is now officially relying on 'community' support. Good luck with that.

**Comment by MHimken** [comment]
Hey Aaron,
I should've guessed as much 👍 So lets try. As a non-native speaker I apologize for hard to understand sentences beforehand.

Example1: Remove the local machine from a collection named "TestDevices". To avoid any prompts ` -Force ` was attached. Otherwise if the machine is found in the target collection a request prompt for the deletion will be shown.

```powershell
$ComputerName = $env:ComputerName
Remove-CMCollectionDirectMembershipRule -CollectionName 'TestDevices' -ResourceName $ComputerName -Force
```

I think I will try editing the rest via the alternative method (submitting an edit). I need to get a feeling first for wording generally used for examples, hints etc. 

Regards
Martin

**Comment by aczechowski** [comment]
Thanks @MHimken, I'll get this added, and revise the article in general. I'll take a swing through the other related articles as well to make sure they are all in proper order too.
