### ISSUE TITLE
-Name is not a valid parameter

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#195]
Examples show using 'Start-CMTaskSequenceDeployment -Name' yet -Name is not a valid parameter.

Start-CMTaskSequenceDeployment : A parameter cannot be found that matches parameter name 'Name'.
At line:1 char:32
Start-CMTaskSequenceDeployment -Name

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 5eb1d4a1-adac-90af-e74d-dc65bc6660b1
* Version Independent ID: 5f871428-3df3-4676-dce0-255ecbb65f86
* Content: [Start-CMTaskSequenceDeployment (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/start-cmtasksequencedeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Start-CMTaskSequenceDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Start-CMTaskSequenceDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for the feedback.
