### ISSUE TITLE
Related Links to New-CMTaskSequence broken

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#196]
Your Hypertext link to New-CMTaskSequence in Related Links points to Get-CMTaskSequence

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3773b0-ff5a-cf7d-0b1f-966de76b578e
* Version Independent ID: 5ec2f497-164c-5c45-47f1-74ffa3aa93d2
* Content: [Get-CMTaskSequence (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmtasksequence?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMTaskSequence.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMTaskSequence.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for the feedback, likely a copy/paste error 😞

**Comment by aczechowski** [comment]
There was a similar issue in the other linked articles. And they were all linking to themselves. I fixed them all. This issue will auto close when my change merges. It will then go live with the next daily publishing cycle, which should be later today.
