### ISSUE TITLE
Incorrect description of what the cmdlet does

### ISSUE THREAD

**Issue by jensronnbom** [MicrosoftDocs/sccm-docs-powershell-ref#199]
This is stated in the documentation for the cmdlet: 
"The Get-CMDeploymentTypeSupersedence cmdlet gets supersedence objects for a superseded deployment type. Required input is a superseded deployment type."

This is incorrect according to my tests. 
It should be the reverse. 
It gets supersedence objects for a supersed**ing** deployment type. 
Required input is a supersed**ing** deployment type. 
It returns supersed**ed** deployment types. 

The info for the InputObject parameter is correct however. 
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 13c05091-23b2-44bb-5435-071f00d83186
* Version Independent ID: 0d145552-fe34-09b5-38ec-1b7e7eaebe25
* Content: [Get-CMDeploymentTypeSupersedence (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdeploymenttypesupersedence?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDeploymentTypeSupersedence.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDeploymentTypeSupersedence.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jensronnbom for the feedback.

**Comment by aczechowski** [comment]
I'm revising to avoid the confusion of the terms, using the same language that we have in the console such as "old" and "replacement". I'm also updating the example with more detail. Thanks again for the feedback.
