### ISSUE TITLE
Unable to create second deployment type for existing application while reusing detectionchecks

### ISSUE THREAD

**Issue by AndrzejWojtowicz** [MicrosoftDocs/sccm-docs-powershell-ref#200]
I have existing ```$SCCMDetectionChecks ``` ArrayList where I am storing all detection clauses. 

Then I am running 
```Add-CMScriptDeploymentType -ApplicationName $SCCMApplicationName -AddDetectionClause $SCCMDetectionChecks ```

and it works fine. However while trying to add second deployment type to existing application SCCM i get the below error:
```
ConfigMgr Error Object:
instance of SMS_ExtendedStatus
{
	Description = "The digest is not valid";
	ErrorCode = 1078462235;
	File = "..\\sspconfigurationitem.cpp";
	Line = 1981;
	Operation = "PutInstance";
	ParameterInfo = "";
	ProviderName = "ExtnProv";
	SQLMessage = "[42000][3998][Microsoft][SQL Server Native Client 11.0][SQL Server]Uncommittable transaction is detected at the end of the batch. The transaction is rolled back.";
	SQLSeverity = 16;
	SQLStatus = 3998;
	StatusCode = 2147749889;
};
```

I have found some info on the internet that reusing existing detection clause objects might be causing this but was unable to narrow down the issue or find a workaround.

Any ideas?

**Comment by AndrzejWojtowicz** [comment]
I have found a workaround - re-instantiate detection clause objects and then it works. 
This is still not a permanent solution though.

**Comment by aczechowski** [comment]
Thanks @AndrzejWojtowicz for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
