### ISSUE TITLE
New-CMApplication : The specified language 'en-US' does not exist in the current catalogs.

### ISSUE THREAD

**Issue by PehDeh** [MicrosoftDocs/sccm-docs-powershell-ref#201]
Hi,

Creating an Application with this Command:
New-CMApplication -Name $Name -Description $Description -Publisher $Publisher -AutoInstall $true -SoftwareVersion $SoftwareVersion -IconLocationFile $IconLocationFile -DefaultLanguageId 1033
Leads to an errormessage:
New-CMApplication : The specified language 'en-US' does not exist in the current catalogs.

From the Documentation i guess it must be LCID 1033 since you state In32.

Creating the Application manual will use default en-US for the Application, so it should be available.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: acbfae92-9a93-8b37-615e-fd709afadee3
* Version Independent ID: c922bbf0-b47b-3c10-70d4-206ba62c70fd
* Content: [New-CMApplication (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmapplication?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMApplication.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMApplication.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PehDeh for the feedback. Let me check with engineering...

**Comment by PehDeh** [comment]
I modified the powershell Witz set-Culture to en-us then it worked.But making it dependend on the culture in ps but not making it dependend in the GUI feels Strange.GMX Mail AppAm 28.10.20 um 20:22 schrieb Aaron Czechowski
                
            
            
                
                    Von: "Aaron Czechowski" <notifications@github.com>Datum: 28. Oktober 2020An: "MicrosoftDocs/sccm-docs-powershell-ref" <sccm-docs-powershell-ref@noreply.github.com>Cc: "PehDeh" <patrick.dorsch@gmx.de>,"Mention" <mention@noreply.github.com>Betreff: Re: [MicrosoftDocs/sccm-docs-powershell-ref] New-CMApplication : The specified language 'en-US' does not exist in the current catalogs. (#201)
                
                
Thanks @PehDeh for the feedback. Let me check with engineering...

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/issues/201#issuecomment-718155611",
"url": "https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/issues/201#issuecomment-718155611",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by ameltzerMSFT** [comment]
Hi @PehDeh. What you're describing seems like a bug in the cmdlet, especially if it does not reproduce in the UI. 

Can you please use the 🙂 button in the console to send us a frown and provide more details about the issue? We will investigate this further.

**Comment by aczechowski** [comment]
Thanks @ameltzerMSFT 😄 

@PehDeh I'm closing this issue as product feedback, and nothing actionable for docs right now. Thank you for filing the feedback!
