### ISSUE TITLE
Parameters: -AvaliableDate -AvaliableTime

### ISSUE THREAD

**Issue by vlepineadm** [MicrosoftDocs/sccm-docs-powershell-ref#205]
Hello,
During a test I'm using example 1 on this page, I noticed that there was a fault on the following parameters: -AvaliableDate -AvaliableTime instead of -AvailableDate -AvailableDateTime.
Thank you for your consideration.

Valentin

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6969261b-81a1-8b64-29f9-08b77c618983
* Version Independent ID: 3482ebd5-2bfc-033f-7936-e6081e42b526
* Content: [Set-CMApplicationDeployment (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmapplicationdeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMApplicationDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMApplicationDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @vlepineadm for the feedback. I'll get this fixed shortly
