### ISSUE TITLE
Working example

### ISSUE THREAD

**Issue by AlBrough** [MicrosoftDocs/sccm-docs-powershell-ref#206]
This example works using this cmdlet
New-CMApplicationDeployment -Name "Visual Studio 2019" -AvailableDateTime '01/01/2020 00:00:00' -CollectionName 'Developers Workstation' -DeadlineDateTime '01/01/2020 00:00:00' -DeployAction Install -DeployPurpose Required

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 133bdcaf-98f7-c4bd-02bd-d8e87f396b17
* Version Independent ID: bfe9d168-352a-0047-612e-f40560aa7467
* Content: [New-CMApplicationDeployment (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmapplicationdeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMApplicationDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMApplicationDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AlBrough for sharing this example! I'll get it added shortly.

In the future, I encourage you to submit the change yourself. For more information, see [How to use the docs](https://docs.microsoft.com/mem/use-docs#contribute).
