### ISSUE TITLE
Breaking Changes Not Listed for New-CMDetectionClauseFile

### ISSUE THREAD

**Issue by AdamGrossTX** [MicrosoftDocs/sccm-docs-powershell-ref#208]
The CmdLet New-CMDetectionClauseFile an -ExpressionOperator parameter that accepts an ENUM value.  In ConfigMgr 2006 and previous, the ENUM was of type:
[Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.RuleExpressionOperator]

In ConfigMgr 2010 the type has changed to:
[Microsoft.ConfigurationManagement.Cmdlets.Dcm.Commands.FileFolderRuleExpressionOperator]

This is a breaking change and requires additional coding to determine which ENUM type is supported.

This change is also reflected in the docs for New-CMDetectionClauseFile. 
https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmdetectionclausefile?view=sccm-ps

The breaking change should be listed here and possibly noted on the New-CMDetectionClauseFile doc as well.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1ed40668-dcf6-0c28-7001-43b4581f50f2
* Version Independent ID: ef828e10-f8db-07f5-ba71-cf4354b2730d
* Content: [Version 2010 release notes - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/2010-release-notes?view=sccm-ps#cmdlet-changes)
* Content Source: [docs-conceptual/2010-release-notes.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/2010-release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AdamGrossTX for catching this. It helped us highlight a gap in our release note process. 😀
