### ISSUE TITLE
Examples use incorrect parameter

### ISSUE THREAD

**Issue by Ghostmokey582** [MicrosoftDocs/sccm-docs-powershell-ref#21]
Both examples in this article use a parameter which is not valid "-UncFileLocation" and do not include the mandatory parameter "-Path." Now it is pretty obvious this -UncFileLocation should actually be -Path by the way it is used, but this really ought to be corrected.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: eb86dc07-c360-4eb5-3d77-eebd80d1aeef
* Version Independent ID: 1597a12b-2d3c-39d5-ebf1-181156ad7de4
* Content: [Import-CMDriver (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/ConfigurationManager/Import-CMDriver?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Import-CMDriver.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Import-CMDriver.md)

**Comment by aczechowski** [comment]
Thanks @Ghostmokey582 for the feedback. It looks like **UncFileLocation** is an alias for **Path**, but we try to avoid using aliases in our examples. I'll update it now, as well as give the article a general review.

The issue will auto-close when my changes merge, and then will be live with the next daily publishing cycle (~4 PM Pacific)
