### ISSUE TITLE
  [-ContentLocation <String>]

### ISSUE THREAD

**Issue by PaulKlerkx** [MicrosoftDocs/sccm-docs-powershell-ref#210]
I don't believe this switch works correctly, could you add an example 
For Set-CMScriptDeploymentType and Set-CMWindowsAppxDeploymentType - these work as expected for those types of Deployment Type with just the content location ( no file names required. )
For Set-CMMSIDeploymentType, it appears you don't use a content location, you have to use a file path. 
If you browse to the content location for the MSI, locate an MSI in there and append that to the content location, this then updates the content location, HOWEVER, it also wipes the current installation command and replaces it with a generic msi installation commandline for the MSI you appended to the command.

maybe just an example of ONLY changing the content path without modifying the installation properties. 

this is what I would think the command should be 
set-CMMsiDeploymentType -ApplicationName 'MyApp' -DeploymentTypeName 'MyDType - Windows Installer (*.msi file)' -ContentLocation '\\myserver\myapp\V1'

If I use this (which updates the content path, it also wipes my installation command. )
set-CMMsiDeploymentType -ApplicationName 'MyApp' -DeploymentTypeName 'MyDType - Windows Installer (*.msi file)' -ContentLocation '\\myserver\myapp\V1\myMSIv1.msi'

that is, rather than this command
set-CMMsiDeploymentType -ApplicationName 'MyApp' -DeploymentTypeName 'MyDType - Windows Installer (*.msi file)' -ContentLocation '\\myserver\myapp\V1'

I use this (which updates the content path, but also wipes my installation command. )
set-CMMsiDeploymentType -ApplicationName 'MyApp' -DeploymentTypeName 'MyDType - Windows Installer (*.msi file)' -ContentLocation '\\myserver\myapp\V1\myMSIv1.msi'

*******************************************************************
For a **Script** Deployment Type, this command works - that is, it ONLY changes the content path without changing the installation properties

set-CMScriptDeploymentType -ApplicationName 'MyApp' -DeploymentTypeName 'MyDType' -ContentLocation '\\myserver\myapp\V1'
************************************************************
For an **Appx** Deployment Type, this command works - that is, it ONLY changes the content path without changing the installation properties

set-CMWindowsAppxDeploymentType -ApplicationName 'MyApp' -DeploymentTypeName 'Windows app package (*.appx, *.appxbundle)' -ContentLocation '\\myserver\myapp\V1'

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b2ed382-df64-0705-8d70-a74ab4032d6f
* Version Independent ID: 0400a5c5-6659-85ee-dbec-8ca6fa163d54
* Content: [Set-CMWindowsAppxDeploymentType (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmwindowsappxdeploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMWindowsAppxDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMWindowsAppxDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @PaulKlerkx, I'm checking with the engineering team, I wonder if this is a bug?

Also, the feedback is assigned to the **Set-CMWindowsAppxDeploymentType** cmdlet (appx), but it seems like you're talking about the **Set-CMMsiDeploymentType** cmdlet (MSI)? Just making sure...

**Comment by aczechowski** [comment]
Assuming that the thrust of your feedback is around Set-CMMsiDeployment...we do have a couple of product bugs for it, specifically one about how changing the content location resets the DT. It would also improve the cmdlet to match the UI experience, where supposedly you can specify either a file or folder path.

I can't make any promises as to when those changes will happen, but it looks promising for a release later this year 😉 So I'm going to close this issue and not make any changes to the article, and wait for the changes to the cmdlet.
