### ISSUE TITLE
Example wrong?

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/sccm-docs-powershell-ref#211]
I'm trying to set User Category, but it constantly fails.
I've tried using an input variable, I've tried using a string, always fails
```PowerShell
$NewIPUApp = New-CMApplication -Name $IPUAppName -Publisher "OneVinn" -LocalizedName $IPUAppName -LocalizedDescription "Upgrades PC to $Release"
$IPUAppUserCat = New-CMCategory -CategoryType UserCategories -Name "IPUApplication"
Set-CMApplication -InputObject $NewIPUApp -AddUserCategory $IPUAppUserCat
```

Fails with
```
PS PS2:\>         Set-CMApplication -InputObject $NewIPUApp -AddUserCategory $IPUAppUserCat

Set-CMApplication : The specified category 'UserCategories:c4cb64e6-7eb2-4094-bb27-10959d024994' does not exist.
At line:1 char:9
+         Set-CMApplication -InputObject $NewIPUApp -AddUserCategory $I ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Confi....SetApplication:SetApplication) [Set-CMApplication], InvalidOperationException
    + FullyQualifiedErrorId : ValidationFailed,Microsoft.ConfigurationManagement.Cmdlets.AppMan.Commands.SetApplication
 

PS PS2:\>         Set-CMApplication -InputObject $NewIPUApp -AddUserCategory "IPUApplication"

Set-CMApplication : Cannot bind parameter 'AddUserCategory'. Cannot convert the "IPUApplication" value of type "System.String" to type 
"Microsoft.ConfigurationManagement.ManagementProvider.IResultObject".
At line:1 char:68
+ ... Application -InputObject $NewIPUApp -AddUserCategory "IPUApplication"
+                                                          ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Set-CMApplication], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.ConfigurationManagement.Cmdlets.AppMan.Commands.SetApplication
```
---

Same results if I just use the String Name "IPUApplication"

Ideas?
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a5b3f21-7b20-c783-6984-f80d281f33a6
* Version Independent ID: 4ac02258-93b5-baba-2cd5-3519e1210708
* Content: [Set-CMApplication (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmapplication?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMApplication.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMApplication.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @gwblok, the value type for this parameter is `IResultObject[]` so I think you're correct that the example is wrong by passing strings.

Also, there's a note on the **AddUserCategory** parameter: 

> Only categories of the type CatalogCategories are supported.

[Get-CMCategory](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmcategory?view=sccm-ps) lists the category types, which includes AppCategories, CatalogCategories, and UserCategories. I honestly don't know the difference. But the following worked for me:

```powershell
PS OPC:\> Get-CMCategory -Name "Test Applications" -CategoryType CatalogCategories


SmsProviderObjectPath         : SMS_CategoryInstance.CategoryInstanceID=1597
CategoryInstance_UniqueID     : CatalogCategories:fd0db836-d67f-4e6a-a472-0db9fea1a702
CategoryInstanceID            : 1597
CategoryTypeName              : CatalogCategories
LocalizedCategoryInstanceName : Test Applications
LocalizedInformation          : {Test Applications}
LocalizedPropertyLocaleID     : 0
ParentCategoryInstanceID      : 0
SourceSite                    : OPC


PS OPC:\>$cat = Get-CMCategory -Name "Test Applications"
PS OPC:\>$app = Get-CMApplication -Name "test #1"
PS OPC:\>Set-CMApplication -InputObject $app -AddUserCategory $cat
```

I should note: the command worked, and I could see in the **SDMPackageXML** property of the app again that it included the UserCategories section with the GUID that matches the category. My console isn't working right now, so I can't actually do a visual test in the console, or even roundtrip into Software Center. But I assume there's some reason why the Set-CMApplication article says that the -AddUserCategory only accepts the CatalogCategories type objects.

I hope that helps. I'll keep this issue to clean up the example here.

**Comment by gwblok** [comment]
Thank you.
I was able to update my code and get it working and confirmed in the app
was updated in the console.
