### ISSUE TITLE
Description update

### ISSUE THREAD

**Issue by Barleyologist** [MicrosoftDocs/sccm-docs-powershell-ref#212]
This could use a better description.  I was thinking this would get the status of a distribution, i.e. did the bits make it to the DP (Green).  If that is was this is doing I do not see that information in the results.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 93365baa-ff01-7554-9230-1acaf35764ef
* Version Independent ID: ca716a63-5604-be52-af85-30c84f3545ae
* Content: [Get-CMDistributionStatus (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdistributionstatus?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDistributionStatus.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDistributionStatus.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @Barleyologist for the feedback. That is the purpose of the cmdlet, you just need to interpret the results. The output is the WMI class [SMS_ObjectContentExtraInfo](https://docs.microsoft.com/mem/configmgr/develop/reference/core/servers/console/sms_objectcontentextrainfo-server-wmi-class). So for example, here's a console screenshot for the client package in a test environment:

![image](https://user-images.githubusercontent.com/26784733/112917404-656d2a00-90b7-11eb-960f-0ce29b090225.png)

Then here's the output of that cmdlet for that same package:

```output
SmsProviderObjectPath : SMS_ObjectContentExtraInfo.ObjectID="XYZ00003"
DateCreated           : 3/25/2021 10:11:55
Description           : This package is automatically created and distributed so that client can upgrade itself from
                        the closest distribution point.
FeatureType           : 8
LastUpdateDate        : 3/25/2021 10:24:26
NumberErrors          : 0
NumberInProgress      : 0
NumberSuccess         : 4
NumberUnknown         : 0
ObjectID              : XYZ00003
ObjectType            : 0
ObjectTypeID          : 2
PackageID             : XYZ00003
SoftwareName          : Microsoft Corporation Configuration Manager Client Package
SourceSite            : XYZ
SourceSize            : 401984
SourceVersion         : 237
Targeted              : 4
```

See the properties **Targeted** and **NumberSuccess** align with the screenshot.

So you could use this to look at the **NumberErrors** property to make sure things didn't go awry.

I'll add some of this detail to the article and generally clean it up.

Does that answer your question?
