### ISSUE TITLE
Examples are blank

### ISSUE THREAD

**Issue by AbfSailor** [MicrosoftDocs/sccm-docs-powershell-ref#215]
Examples are blank

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4a79c542-deb3-ae2b-56e0-520a562efef4
* Version Independent ID: 31c6a2a3-2f17-d6bc-fb27-28f4d1ec9ec4
* Content: [Remove-CMApplicationDeployment (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmapplicationdeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMApplicationDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMApplicationDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by XxQuaDxX** [comment]
Same for Get-CMSoftwareUpdateCategory

**Comment by aczechowski** [comment]
Thanks @AbfSailor and @XxQuaDxX for the feedback. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). Starting with version 2002, the article for any new cmdlet should be mostly complete. It's a work in progress to bring these pages up to a bare minimum of information. I'll try to get information added for these two cmdlets soon.
