### ISSUE TITLE
Get-CMComponentStatusSetting wrong behaviour

### ISSUE THREAD

**Issue by jleu84** [MicrosoftDocs/sccm-docs-powershell-ref#216]
Wrong behaviour in commandlet: Get-CMComponentStatusSetting:

`[DBG]: PS SCS:\>> $comp = Get-CMComponentStatusSetting -ComponentName "AI_UPDATE_SERVICE_POINT"

[DBG]: PS SCS:\>> $comp.Count
2

[DBG]: PS SCS:\>> $comp[0]

ComponentName                          : AI_UPDATE_SERVICE_POINT
ErrorMessagesCriticalThreshold         : 5
ErrorMessagesWarningThreshold          : 1
InformationalMessagesCriticalThreshold : 5000
InformationalMessagesWarningThreshold  : 2000
Name                                   : SMS Site Server
SiteCode                               : SCS
ThresholdPeriod                        : Since 00:00:00
WarningMessagesCriticalThreshold       : 50
WarningMessagesWarningThreshold        : 10

ComponentName                          : AI_UPDATE_SERVICE_POINT
ErrorMessagesCriticalThreshold         : 5
ErrorMessagesWarningThreshold          : 1
InformationalMessagesCriticalThreshold : 5000
InformationalMessagesWarningThreshold  : 2000
Name                                   : SMS Site Server
SiteCode                               : PS1
ThresholdPeriod                        : Since 00:00:00
WarningMessagesCriticalThreshold       : 50
WarningMessagesWarningThreshold        : 10

[DBG]: PS SCS:\>> $comp[1]

ComponentName                          : AI_UPDATE_SERVICE_POINT
ErrorMessagesCriticalThreshold         : 5
ErrorMessagesWarningThreshold          : 1
InformationalMessagesCriticalThreshold : 5000
InformationalMessagesWarningThreshold  : 2000
Name                                   : SMS Site Server
SiteCode                               : SCS
ThresholdPeriod                        : Since 00:00:00
WarningMessagesCriticalThreshold       : 50
WarningMessagesWarningThreshold        : 10

ComponentName                          : AI_UPDATE_SERVICE_POINT
ErrorMessagesCriticalThreshold         : 5
ErrorMessagesWarningThreshold          : 1
InformationalMessagesCriticalThreshold : 5000
InformationalMessagesWarningThreshold  : 2000
Name                                   : SMS Site Server
SiteCode                               : PS1
ThresholdPeriod                        : Since 00:00:00
WarningMessagesCriticalThreshold       : 50
WarningMessagesWarningThreshold        : 10

[DBG]: PS SCS:\>> Get-CMComponentStatusSetting -ComponentName "AI_UPDATE_SERVICE_POINT" | Where-Object {$_.SiteCode -match "PS1"}

ComponentName                          : AI_UPDATE_SERVICE_POINT
ErrorMessagesCriticalThreshold         : 5
ErrorMessagesWarningThreshold          : 1
InformationalMessagesCriticalThreshold : 5000
InformationalMessagesWarningThreshold  : 2000
Name                                   : SMS Site Server
SiteCode                               : SCS
ThresholdPeriod                        : Since 00:00:00
WarningMessagesCriticalThreshold       : 50
WarningMessagesWarningThreshold        : 10

ComponentName                          : AI_UPDATE_SERVICE_POINT
ErrorMessagesCriticalThreshold         : 5
ErrorMessagesWarningThreshold          : 1
InformationalMessagesCriticalThreshold : 5000
InformationalMessagesWarningThreshold  : 2000
Name                                   : SMS Site Server
SiteCode                               : PS1
ThresholdPeriod                        : Since 00:00:00
WarningMessagesCriticalThreshold       : 50
WarningMessagesWarningThreshold        : 10`

(admin edit: add link to article for proper tracking)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe9d90a-20c7-d46e-3fa6-8ed10ddbb57c
* Version Independent ID: 75269c86-ced5-f423-2fb0-89d47b638213
* Content: [Get-CMComponentStatusSetting (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmcomponentstatussetting?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMComponentStatusSetting.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMComponentStatusSetting.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @jleu84, this looks like a product issue, please file [Product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) to get an item in to the engineering team to investigate. I tried the same cmdlet in our test environment, and while the console only shows one instance of a component, the cmdlet returns 10 items, and the object count is four. Weird 🤔

The article for this cmdlet does have some issues, such as referencing the **SiteCode** parameter in an example, but that parameter doesn't exist for this cmdlet. So I'll at least address that issue, and will close this item when that's complete.
