### ISSUE TITLE
acceptable values for -Priority is incorrect

### ISSUE THREAD

**Issue by scott-ip1** [MicrosoftDocs/sccm-docs-powershell-ref#221]
the "-priority" section has "increase, decrease" as acceptable values, bet then has "high, normal, low" in the table under it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d26194af-5a42-bf14-13bd-ef213affc13a
* Version Independent ID: 866d53e6-6916-2035-9508-be25c169524e
* Content: [Set-CMPackage (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmpackage?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMPackage.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMPackage.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @scott-ip1 for the feedback. I'll fix this up today, and review the article all-up as well. Always look at the **Accepted values** field, that's a YAML table auto-generated from the module. The text just below the parameter name is a human-entered description, and I've seen a number of instances where they're wrong. I'm generally just removing those extra lists, unless they have some additional description about the values.
