### ISSUE TITLE
DisplaySupersedenceInApplicationCatalog

### ISSUE THREAD

**Issue by PascalVerbruggen** [MicrosoftDocs/sccm-docs-powershell-ref#222]
-DisplaySupersedenceInApplicationCatalog
The documentation states that this option mustn't be used anymore as the application catalog doesn't exist anymore.

However the end-user GUI functionality moved from the application catalog to the Software Center application on the client.
This option still works and still offers - as near as I can tell - the same functional behavior.
It checks or unchecks "allow users to see deployments for this application and all applications that it supersedes in Software Center ..." in the management console.
(I do agree that the name is confusing.)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8a5b3f21-7b20-c783-6984-f80d281f33a6
* Version Independent ID: 4ac02258-93b5-baba-2cd5-3519e1210708
* Content: [Set-CMApplication (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmapplication?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMApplication.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMApplication.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @PascalVerbruggen, good feedback! I'll change that today. 
You might also consider filing [product feedback](https://docs.microsoft.com/mem/configmgr/core/understand/product-feedback) to suggest to the engineering team to rename the parameter (and keep the current name as an alias for backwards compatibility). 😉
