### ISSUE TITLE
Missing description and example..

### ISSUE THREAD

**Issue by MatthewCKelly** [MicrosoftDocs/sccm-docs-powershell-ref#224]
missing several sections to the document..

- {{ Fill in the Synopsis }}
- {{ Fill in the Description }}
- PS XYZ:\> {{ Add example code here }}
- {{ Add example description here }}

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 09ef7dc5-65f2-5f8e-f7b1-155345aa3b97
* Version Independent ID: 9f95facc-3072-8317-5311-57fc78114780
* Content: [Get-CMBoundaryGroupSiteSystem (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmboundarygroupsitesystem?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMBoundaryGroupSiteSystem.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMBoundaryGroupSiteSystem.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @MatthewCKelly for the feedback. I made updates to this article, and will publish it soon (along with the 2107 detailed updates)
