### ISSUE TITLE
documentation errors

### ISSUE THREAD

**Issue by ramspede** [MicrosoftDocs/sccm-docs-powershell-ref#226]
A couple of sections look like they were copied/pasted from another section, and are not appropriate.

-ThreatID
-ThreatName
-InputObject : Specify a detected malware object.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 16ff7c87-4a87-83d2-8f4a-8ff320ba85de
* Version Independent ID: 221e6ea5-27a9-2ff3-849f-890d724c9242
* Content: [Get-CMDevice (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdevice?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDevice.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDevice.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @ramspede, those are actually accurate. 😄 I revised this article recently, and tested those options. I agree they seem a little misplaced.
