### ISSUE TITLE
New-CMPackageDeployment description not accurate

### ISSUE THREAD

**Issue by jessiewestlake** [MicrosoftDocs/sccm-docs-powershell-ref#228]
The description for `New-CMPackageDeployment` states that the cmdlet allows you to set when the deployment expires, but you cannot use the cmdlet to set the expiration. Strangely, the cmdlet does have a parameter *-UseUtcForExpireSchedule* to mark the expiration time as using UTC, but you cannot actually set the expiration. Not only is the documentation incorrect, the missing capability in the cmdlet is a huge shortfall. The `Start-CMPackageDeployment` and `Set-CMPackageDeployment` cmdlets allow you to set an expire time, but the `Start-CMPackageDeployment` cmdlet is deprecated.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cabfb7b9-3081-8d55-263c-c6a21a1b995b
* Version Independent ID: a1f405c5-475d-af54-1733-0d3cb0e08fc4
* Content: [New-CMPackageDeployment (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmpackagedeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMPackageDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMPackageDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jessiewestlake for the feedback. I'll review and update when I get time.

As for missing capability in the cmdlet itself, please file [product feedback](https://docs.microsoft.com/powershell/sccm/overview#feedback-for-powershell) to let the engineering team know.

**Comment by aczechowski** [comment]
Actually, I figured this out for task sequence deployments, and didn't transfer the descriptions to other articles like this one. (I'm doing that now, should publish later tonight). 

- **DeadlineDateTime**: when the deployment _expires_. 
- **Schedule**: The deployment _deadline_ (assignment)
- **AvailableDateTime**: when the deployment is _available_
