### ISSUE TITLE
Get-CMDriverPackage does not have a -Fast parameter

### ISSUE THREAD

**Issue by patrick-massie** [MicrosoftDocs/sccm-docs-powershell-ref#229]
Probably never had. For sure not in MECM 2010

(admin edit: adding article metadata for proper linking)
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3a9966dd-7274-f19b-f475-8020b1e9c15c
* Version Independent ID: abbb4f07-1e2c-931f-0c9f-1aca910af755
* Content: [Get-CMDriverPackage (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/Get-CMDriverPackage?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDriverPackage.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDriverPackage.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @patrick-massie, yep, that parameter was added to a bunch of cmdlets in version 2103, see [Version 2103 release notes](https://docs.microsoft.com/powershell/sccm/2103-release-notes#fast-support).

The docs are mostly auto-generated from the latest version of the module, we then do some cleanup and adding some descriptions and examples. But if the syntax at the top of the article includes a parameter, you can trust that it's at least in the latest version of the module itself.
