### ISSUE TITLE
Does this cmdlet work?

### ISSUE THREAD

**Issue by elang-bmrn** [MicrosoftDocs/sccm-docs-powershell-ref#23]
When I try to run this command on a fresh 1810 install, I receive this error:

PS NA1:\&gt; Set-CMBoundaryGroupRelationship -SourceGroupId 16777233 -DestinationGroupId 16777221
Set-CMBoundaryGroupRelationship : No object corresponds to the specified parameters.
At line:1 char:1
+ Set-CMBoundaryGroupRelationship -SourceGroupId 16777233 -DestinationG ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Confi...tionshipCommand:SetBoundaryGroupRelationshipCommand)
   [Set-CMBoundaryGroupRelationship], ItemNotFoundException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.ConfigurationManagement.Cmdlets.HS.Commands.SetBoundaryGroupRelat
   ionshipCommand

PS NA1:\&gt; Set-CMBoundaryGroupRelationship -SourceGroupId 16777233 -DestinationGroupId 16777221 -FallbackDPMinutes 120 -F
allbackMPMinutes 120 -FallbackSmpMinutes 0
Set-CMBoundaryGroupRelationship : No object corresponds to the specified parameters.
At line:1 char:1
+ Set-CMBoundaryGroupRelationship -SourceGroupId 16777233 -DestinationG ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Confi...tionshipCommand:SetBoundaryGroupRelationshipCommand)
   [Set-CMBoundaryGroupRelationship], ItemNotFoundException
    + FullyQualifiedErrorId : ItemNotFound,Microsoft.ConfigurationManagement.Cmdlets.HS.Commands.SetBoundaryGroupRelat
   ionshipCommand

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d4d31234-5ab1-0485-b992-8c56837ebaa7
* Version Independent ID: f2aabca6-ab4b-61ec-0d0e-00453cfb85a0
* Content: [Set-CMBoundaryGroupRelationship (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmboundarygrouprelationship?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMBoundaryGroupRelationship.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMBoundaryGroupRelationship.md)

**Comment by DavidRiberot** [comment]
Hi, I have the same problem... First instanciation is okay but when I try to set multiple values (either Source or Destination Boundary group), I face the same error :-(

**Comment by aczechowski** [comment]
Thanks for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.

p.s. you can also use the [Product feedback](https://docs.microsoft.com/sccm/core/understand/find-help#product-feedback) process to report such product issues.
