### ISSUE TITLE
New-CMMaintenanceWindow    [-ApplyTo <MaintenanceWindowApplyTo>]    [-ApplyToSoftwareUpdateOnly]    [-ApplyToTaskSequenceOnly]    [-InputObject] <IResultObject>    [-IsEnabled <Boolean>]    [-IsUtc <Boolean>]    -Name <String>    -Schedule <IResultObject>    [-DisableWildcardHandling]    [-ForceWildcardHandling]    [-WhatIf]    [-Confirm]    [<CommonParameters>]

### ISSUE THREAD

**Issue by gguyza001** [MicrosoftDocs/sccm-docs-powershell-ref#231]
สถานที่ทำงานยุคใหม่เริ่มจาก Surface สำหรับธุรกิจ
Surface และ Microsoft 365 มอบอิสระในการทำงานได้จากทุกที่ให้กับผู้ใช้ พร้อมปกป้องกันด้วยการรักษาความปลอดภัยและความสามารถในการจัดการที่ทันสมัยของ

**Comment by aczechowski** [comment]
Via web translation:

> The modern workplace starts with Surface for Business.
Surface and Microsoft 365 give users the freedom to work anywhere. while protecting each other with state-of-the-art security and manageability

Marking this as a test issue and closing.
