### ISSUE TITLE
Remove ALL Device Affinity from ALL users

### ISSUE THREAD

**Issue by MooreSys** [MicrosoftDocs/sccm-docs-powershell-ref#235]
How can I remove all Device Affinity from ALL users? Over 30K users, and the device Affinity is all screwed up. Would like to allow SCCM to rebuild with new Affinity Policy put in place. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 212c7c70-c74e-0a18-53b2-36df09fb6d4e
* Version Independent ID: 3d940e6b-9bce-9f1a-3650-39ca9b6fc0b3
* Content: [Remove-CMUserAffinityFromDevice (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmuseraffinityfromdevice?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMUserAffinityFromDevice.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMUserAffinityFromDevice.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @MooreSys, I would think that you could use this cmdlet to achieve that. I'm no expert on UDA, but I _think_ it's just a database link between the two objects, and this cmdlet would remove that link. So loop through all devices and pass it into this cmdlet to remove the affinity.
Your question is probably better suited towards another channel for the best level of support:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/topics/mem-cm-sdk.html). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to open a case with professional support.
- Contact your Microsoft account team, such as a Customer Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
