### ISSUE TITLE
ConfigMGR - Powershell Commandlet "Get-CMComponentStatusSetting" not working as expected

### ISSUE THREAD

**Issue by jleu84** [MicrosoftDocs/sccm-docs-powershell-ref#236]
[Enter feedback here]

The parameter 'SiteSystemServerName' has been deprecated and may be removed in a future release.
Running: Configuration Manager 2010 Hotfix Rollup (KB46000089)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: afe9d90a-20c7-d46e-3fa6-8ed10ddbb57c
* Version Independent ID: 75269c86-ced5-f423-2fb0-89d47b638213
* Content: [Get-CMComponentStatusSetting (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmcomponentstatussetting?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMComponentStatusSetting.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMComponentStatusSetting.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jleu84 for the feedback. I'll revise the article to note this parameter is deprecated.
