### ISSUE TITLE
Set-CMSoftwareUpdateDeployment RestartServer and RestartWorkstation parameters reversed

### ISSUE THREAD

**Issue by haifisch88** [MicrosoftDocs/sccm-docs-powershell-ref#237]
When running

Set-CMSoftwareUpdateDeployment -RestartServer $false-RestartWorkstation $false

the result is that the deployment is set to not suppress the restart. This logic is reversed, setting the parameters to $false should mean no restart - suppress the restart.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 326524dc-ea0f-211c-28c6-d7d154bb754b
* Version Independent ID: 30356ef1-073d-7d44-3410-727250b97565
* Content: [Set-CMSoftwareUpdateDeployment (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmsoftwareupdatedeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMSoftwareUpdateDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMSoftwareUpdateDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @haifisch88 for the feedback! It's a bug in the doc, I'll change the wording to "Indicate whether to _suppress_ a restart...." The applicable UI settings are described in the following article: https://docs.microsoft.com/mem/configmgr/sum/deploy-use/manually-deploy-software-updates#BKMK_4DeployUpdateGroup (search for "Device restart behavior").

I'll also explicitly note the behavior for using true/false.

**Comment by haifisch88** [comment]
Brilliant, thank you!
