### ISSUE TITLE
Bad Examples

### ISSUE THREAD

**Issue by gwblok** [MicrosoftDocs/sccm-docs-powershell-ref#239]
[Enter feedback here]
The examples on this page are incorrect. You can't actually do them.

I'm having an issue trying to figure out how to add a Configuration Item into a Baseline.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7e6e33e7-c0c2-99d3-8a24-82e3aafb56b4
* Version Independent ID: 9b02d0fe-0969-cddd-5362-1fbf8dc11b71
* Content: [Set-CMBaseline (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmbaseline?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMBaseline.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMBaseline.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by gwblok** [comment]
Thanks for getting back to me
Eventually I did figure out how to get it to work, and I did submit a new
example

**Comment by aczechowski** [comment]
I updated this article (and all *-CMBaseline articles) with better examples, proper descriptions, and general review. FYI, I didn't see your contribution for an example on this one, but will happily help get it added as always! 😄

**Comment by gwblok** [comment]
Thank you!
