### ISSUE TITLE
Typo - CMBoundaryGroup vs. CMBoundary

### ISSUE THREAD

**Issue by EvilerBetty** [MicrosoftDocs/sccm-docs-powershell-ref#24]
Should Example 2 be instead? :   (CMBoundaryGroup vs. CMBoundary)

PS C:\&gt; $BoundaryObj = Get-CMBoundaryGroup -Name "BGroup01", "BGroup02", "BGroup03"
PS C:\&gt; Remove-CMBoundaryGroup -InputObject $BoundaryObj

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 56f33f39-11a3-0c7e-c9e7-b1419d57a872
* Version Independent ID: 3a6febc5-df4e-c9b2-48b6-1f742fe62b72
* Content: [Remove-CMBoundaryGroup (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmboundarygroup?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMBoundaryGroup.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMBoundaryGroup.md)

**Comment by FISHMANPET** [comment]
claiming for mms2019 docathon

**Comment by aczechowski** [comment]
This issue is closed because @FISHMANPET fixed it with his recent contribution, which should publish tomorrow.
