### ISSUE TITLE
Idea for a new Example of using -AddSupportedOperatingSystemPlatform parameter

### ISSUE THREAD

**Issue by dereklangMSFT** [MicrosoftDocs/sccm-docs-powershell-ref#240]
I spent some time to figure out how to use the -AddSupportedOperatingSystemPlatform parameter with set-cmpackage and wanted to submit a simple example that I think might help others.

```
#Sets the OS requirement for a program associated with a standard package
#Replace the values for $ProgramName and $PackageID with your own values
#Replace the value for $Platform with any required OS
$ProgramName = 'Script'
$PackageID = 'ESP0000D'
$Platform = 'All Windows 10 (64-bit) Client'
$OS = Get-CMSupportedPlatform -Name $Platform -Fast
Set-CMProgram -PackageID $PackageID -ProgramName $ProgramName -AddSupportedOperatingSystemPlatform $OS -StandardProgram
```

Thanks

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 4b9f3a57-4b1f-e21d-d4d3-7976620cb554
* Version Independent ID: a78a2dfd-5bd7-12b0-424e-9e60f3ade7b6
* Content: [Set-CMProgram (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmprogram?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMProgram.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMProgram.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @dereklangMSFT for the example! I'll add it to the article
