### ISSUE TITLE
Possible bug or something wrong with New-CMRequirementRuleOperatingSystemValue Description

### ISSUE THREAD

**Issue by boozeman** [MicrosoftDocs/sccm-docs-powershell-ref#241]
In the New-CMRequirementRuleOperatingSystemValue description  says that the -PlatformString  used with CI_ID but you actually have to use ModelName on it.

We can get modelnames it like this:
Get-CMConfigurationPlatform -Name "*Windows 1*" | Select-Object LocalizedDisplayName,ModelName

And then use like this:

$myGC = Get-CMGlobalCondition -Name "Operating System" | Where-Object PlatformType -eq 1
$myRule = $myGC | New-CMRequirementRuleOperatingSystemValue -RuleOperator OneOf -PlatformString "Windows/All_x64_Windows_10_and_higher_Clients","Windows/All_x64_Windows_11_and_higher_Clients"

This was the only way to got it work properly. Is this error or am I missing something?

MECM tested with this is version 2107 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0e70feff-9b07-a4c2-d417-109c51abc754
* Version Independent ID: 9d012cfe-cfde-629a-d3ce-cd317ecdf2ea
* Content: [New-CMRequirementRuleOperatingSystemValue (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmrequirementruleoperatingsystemvalue?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMRequirementRuleOperatingSystemValue.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMRequirementRuleOperatingSystemValue.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @boozeman for the feedback! I thought I had tested that option, but I can reproduce your results now. I'm updating the article with a big refresh I'm working on. Thanks again
