### ISSUE TITLE
Documentation is missing

### ISSUE THREAD

**Issue by TimPeTwo** [MicrosoftDocs/sccm-docs-powershell-ref#242]
This Cmdlet Help is not complete but merely a skeleton. Please provide a proper documentation.
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 28437a50-142a-d893-66ed-6b1016a10e08
* Version Independent ID: 5d3ad092-c912-5253-1bc0-f607ece243f9
* Content: [New-CMScript (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmscript?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMScript.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMScript.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @TimPeTwo for the feedback. We're slowly working through a big backlog of these sorts of issues with this content. I'll pick this up (as well as other related cmdlets) with a big refresh I'm working on with 2111 CB release.
