### ISSUE TITLE
Warning "The specified resource Id '11111111' is of the wrong type

### ISSUE THREAD

**Issue by jasminrueegger** [MicrosoftDocs/sccm-docs-powershell-ref#244]
[Enter feedback here]
Since updating Configuration Manager to 2107, adding a DirectMembershipRule with a Resource-Object generates a Warning and does not add the rule. 
Adding with ResourceID parameter works.

Warning: 
Add-CMDeviceCollectionDirectMembershipRule -CollectionId $collectionid -Resource (Get-CMDevice -name 'TestPC')

Still working:
Add-CMDeviceCollectionDirectMembershipRule -CollectionId $collectionid -ResourceId (Get-CMDevice -name 'TestPC').ResourceId

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c8cbd4-71ba-f0e7-15d2-0d0478d66be9
* Version Independent ID: 600d116d-6403-9621-ded8-0a37753e5ea8
* Content: [Add-CMDeviceCollectionDirectMembershipRule (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmdevicecollectiondirectmembershiprule?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMDeviceCollectionDirectMembershipRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMDeviceCollectionDirectMembershipRule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @jasminrueegger for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I recommend including additional information on your issue when you report it, for more info see https://docs.microsoft.com/powershell/sccm/overview#feedback-for-powershell

I'm closing this issue as there's nothing actionable for docs at this time.

I wasn't able to reproduce the warning that you mentioned, using the same command. My site is now version 2111, so it's possible something changed, but I don't know of any bugs in this area that were fixed for 2111. One thing you might want to check is using the **Resource** parameter with the **Get-CMDevice** cmdlet. Maybe try using the **Get-CMResource** cmdlet, or also include the **Resource** parameter with the **Get-CMDevice** cmdlet. There are subtle differences with those cmdlets that might impact how the object is used with this collection membership rule cmdlet.

**Comment by aczechowski** [comment]
LOL...I just saw this in the [2111 release notes](https://docs.microsoft.com/powershell/sccm/2111-release-notes#add-cmdevicecollectiondirectmembershiprule):

> Fixed an issue when adding a rule by resource object.

So ignore my previous comment! I should have double-checked the release notes first instead of relying on my memory. So update to version 2111 to resolve the issue!

**Comment by jasminrueegger** [comment]
Thanks Aaron

We solved it already when I posted by using get-cmdevice. But I thought it a good idea to include this warning in the docs. Especially, since it prevents the resource from being added to the collection. But now that it is solved, this will not be necessary.

Have a great day
Jasmin

________________________________
