### ISSUE TITLE
cmdlet seems to not work

### ISSUE THREAD

**Issue by AlBrough** [MicrosoftDocs/sccm-docs-powershell-ref#245]
I have the following script below as per the example on the page, it does however not return a result when running the Get-CMDeploymentTypeDetectionClause cmdlet. 
The inputObject variable, when queried, is populated correctly by the Get-CMDeploymentType cmdlet.

`$inputObject = Get-CMDeploymentType -ApplicationName "Office 365 2102 SAC x64 Visio Std"  -DeploymentTypeName "Office 365 Default Deployment Type"`
`Get-CMDeploymentTypeDetectionClause -InputObject $inputObject`

Entries confirmed exist against the application detection.
![image](https://user-images.githubusercontent.com/5189994/144162024-ac359f07-1b8b-4d36-8600-f69dd48bca2e.png)

Running MECM CB 2107

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f685a982-5550-60dc-266f-1b1a4e063b8d
* Version Independent ID: bb103d44-96aa-711f-b21e-df0a3b8dac0c
* Content: [Get-CMDeploymentTypeDetectionClause (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdeploymenttypedetectionclause?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDeploymentTypeDetectionClause.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDeploymentTypeDetectionClause.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @AlBrough for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:

- Post on [Configuration Manager forums](https://docs.microsoft.com/answers/products/mem). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I wasn't able to reproduce your issue, even creating the same registry type detection rule on an app deployment type. The Get-CMDeploymentTypeDetectionClause cmdlet returns the detection rules from the deployment type.

I'm closing this issue as there's nothing actionable for docs at this time.
