### ISSUE TITLE
 site drive: PSProvider name is changed 

### ISSUE THREAD

**Issue by alexslav** [MicrosoftDocs/sccm-docs-powershell-ref#248]
It seems that "AdminUI.PS.Provider\CMSite" PSProvider type-name is no longer valid.

Using the module version 5.2111.1052.1700 and example command to map a site drive gives an error:

`
New-PSDrive -Name "ABC" -PSProvider "**AdminUI.PS.Provider\CMSite**" -Root "siteserver.contoso.com" -Description "Primary site"

$Error[0].ErrorRecord.Exception | Format-List * -Force

ErrorRecord                 : Cannot find a provider with the name 'AdminUI.PS.Provider\CMSite'.
ItemName                    : **AdminUI.PS.Provider\CMSite**
SessionStateCategory        : CmdletProvider
WasThrownFromThrowStatement : False
Message                     : Cannot find a provider with the name 'AdminUI.PS.Provider\CMSite'.
Data                        : {}
InnerException              : 
TargetSite                  : System.Management.Automation.ProviderInfo GetSingleProvider(System.String)
StackTrace                  :    at System.Management.Automation.SessionStateInternal.GetSingleProvider(String name)
                                 at Microsoft.PowerShell.Commands.NewPSDriveCommand.ProcessRecord()
HelpLink                    : 
Source                      : System.Management.Automation
HResult                     : -2146233087

Correct PSProvider that should be used is:
New-PSDrive -Name "ABC" -PSProvider "AdminUI.PS\CMSite" -Root "siteserver.contoso.com" -Description "Primary site"

or just PSProvider "CMSite"
`

---

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3cfeb8-c773-1ae5-0975-ea48e20e4c3a
* Version Independent ID: 7794c3e5-20ad-e389-6e18-c70628a3505a
* Content: [Configuration Manager PowerShell cmdlets - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/overview?view=sccm-ps#feedback)
* Content Source: [docs-conceptual/overview.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/main/docs-conceptual/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-sdk**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @alexslav for the feedback! I had an internal bug for this same issue, which I've fixed in a big update that I'm almost done with 😉 

(reference 12564967)
