### ISSUE TITLE
Missing New-CMAutoDeploymentRule

### ISSUE THREAD

**Issue by chboeye** [MicrosoftDocs/sccm-docs-powershell-ref#257]
I noticed that the "New-CMAutoDeploymentRule" is missing from the list, even though "New-CMAutoDeploymentRuleDeployment" is documented. Is it a work in progress? 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 08ab97f9-ca77-d2f3-1a74-b734033674c5
* Version Independent ID: 01e64fb6-4385-6864-7430-38ac98632aaf
* Content: [ConfigurationManager Module - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/ConfigurationManager.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/main/sccm-ps/ConfigurationManager/ConfigurationManager.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Hi @chboeye, New-CMAutoDeploymentRule is an alias for [New-CMSoftwareUpdateAutoDeploymentRule](https://docs.microsoft.com/powershell/module/configurationmanager/New-CMSoftwareUpdateAutoDeploymentRule). We use the tool PlatyPS to automate most of our PowerShell docs, and it currently doesn't support aliases. You can see the feature request in their backlog: https://github.com/PowerShell/platyPS/issues/128
I'm closing this issue. I recommend that you subscribe to that PlatyPS issue to keep up to date on its progress.
