### ISSUE TITLE
Name for variables

### ISSUE THREAD

**Issue by minou65** [MicrosoftDocs/sccm-docs-powershell-ref#259]
The name for the variables in the hastable must be exact as in the UI and are casesensitiv

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e0622994-fdbf-0592-03d4-d37db9f958f9
* Version Independent ID: 03a7cffe-6a93-3acd-7ba8-6953e774d54a
* Content: [Invoke-CMScript (ConfigurationManager) - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/invoke-cmscript?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Invoke-CMScript.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/main/sccm-ps/ConfigurationManager/Invoke-CMScript.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @minou65 for the feedback. I'm updating content for the 2203 current branch release, and will try to address this article at the same time.

FYI, we rely on community support from members like you to assist. In the future, if you have information to share, I suggest that you submit an edit to the article to contribute your example. For more information, see [How to contribute](https://docs.microsoft.com/mem/use-docs#contribute).
