### ISSUE TITLE
Feature Type Numbers

### ISSUE THREAD

**Issue by mattjoyce** [MicrosoftDocs/sccm-docs-powershell-ref#26]
Please include the Deployment Feature Type mapping from number to type.
      1 = Application
      2 = Package
      3 = Unknown
      4 = Firewall Setting
      5 = SoftWareUpdate
      6 = Configuration Item
      7 = Task Sequence

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2883f68-761d-8193-5b20-51dec837f752
* Version Independent ID: d487ce5f-a031-68de-cbb9-274a4617612b
* Content: [Get-CMDeployment (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDeployment.md)

**Comment by aczechowski** [comment]
What I'll do is update this article to reference the [SMS_DeploymentSummary server WMI class](https://docs.microsoft.com/en-us/mem/configmgr/develop/reference/apps/sms_deploymentsummary-server-wmi-class), which is the output object. That article has a longer and I think more complete list of values. Thanks for the feedback!

This issue will close when the associated PR merges. The changes will publish soon with the 2006 content release.
