### ISSUE TITLE
Invalid URL

### ISSUE THREAD

**Issue by LaurentDardenne** [MicrosoftDocs/sccm-docs-powershell-ref#264]
In this page 
https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/main/docs-conceptual/1810-release-notes.md
the url is invalid (case sensitive) :
```
Configuration Manager current branch version 1806 is the baseline for these changes. For more information, see [Configuration Manager Cmdlet Library changes for version 1806](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/main/docs-conceptual/1806_release_notes.md).
```
Correct https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/main/docs-conceptual/1806_Release_Notes.md

Other pages are concerned : 1806,1802

**Comment by aczechowski** [comment]
Hi @LaurentDardenne, the links work ok from the published articles, https://docs.microsoft.com/powershell/sccm/1810-release-notes
They aren't intended to work from the markdown source file on GitHub. Most often the links are site or file-relative, which definitely don't work when previewing the markdown source.
