### ISSUE TITLE
-ExpressionOperator is listed twice

### ISSUE THREAD

**Issue by alexverboon** [MicrosoftDocs/sccm-docs-powershell-ref#29]
Just cosmetics, but the **-ExpressionOperator** is listed twice

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 34762e49-9276-4a17-eabb-c6e188d14973
* Version Independent ID: 8bdafc0b-6262-9acb-8eee-9f21e1c38c30
* Content: [Add-CMComplianceSettingScript (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmcompliancesettingscript?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMComplianceSettingScript.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMComplianceSettingScript.md)

**Comment by FISHMANPET** [comment]
@aczechowski this is the issue I showed you at the hackathon

**Comment by aczechowski** [comment]
Thanks @FISHMANPET, I'm checking with the engineering team. There's some subtle differences between what's showing in the [raw markdown](https://raw.githubusercontent.com/MicrosoftDocs/sccm-docs-powershell-ref/master/sccm-ps/ConfigurationManager/Add-CMComplianceSettingScript.md), so I want to validate that before making or suggesting any changes. The published article only shows one instance of the parameter, but I'm honestly not sure why. 😕

**Comment by aczechowski** [comment]
This appears to be fixed now. We've done several refreshes of the content since last year, now automated with PlatyPS from the module itself.
