### ISSUE TITLE
Reference Link on this page is dead

### ISSUE THREAD

**Issue by NoelFairclough** [MicrosoftDocs/sccm-docs-powershell-ref#30]
The "Configuration Manager cmdlet reference" link under the NEXT STEPS section, as well as the Reference link on the left hand side goes to a 404 Page Not Found.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7d3cfeb8-c773-1ae5-0975-ea48e20e4c3a
* Version Independent ID: 7794c3e5-20ad-e389-6e18-c70628a3505a
* Content: [Get started with ConfigMgr cmdlets - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/overview?view=sccm-ps#feedback)
* Content Source: [docs-conceptual/overview.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/overview.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @NoelFairclough for reporting this. I fixed this issue once already. I'm checking with our support team to find out why it's coming back.

**Comment by aczechowski** [comment]
There's an underlying bug with this type of content that the docs engineering team is investigating. In the meantime, we've reconfigured this repository with an interim workaround. The 404 is resolved, I'm closing this issue.

**Comment by bryandam** [comment]
@aczechowski: It's doing it again.

**Comment by aczechowski** [comment]
This link works: https://docs.microsoft.com/powershell/module/configurationmanager/configurationmanager?view=sccm-ps

I'm not sure why this keeps happening. :( 
I updated the article (again) with this current link.
