### ISSUE TITLE
 Inaccurate Examples

### ISSUE THREAD

**Issue by PhillyUrbs** [MicrosoftDocs/sccm-docs-powershell-ref#31]
The example used for this cmdlet uses parameters that are no longer supported.
-SecurityScopeAction and -SecurityScopeName
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ed301c28-3547-9638-d82f-691f36ee70b3
* Version Independent ID: f688a5a0-7530-2e11-4e94-6cd991e7aec4
* Content: [Set-CMDistributionPointGroup (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmdistributionpointgroup?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMDistributionPointGroup.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMDistributionPointGroup.md)

**Comment by aczechowski** [comment]
Thanks @PhillyUrbs for the feedback. We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by PhillyUrbs** [comment]
I didn't realize you could submit changes.  I have submitted one for this and will do the same for the other comment I made with a similar issue.

**Comment by AdamGrossTX** [comment]
@aczechowski I'm claiming this issue for #MMS2019Docathon

**Comment by AdamGrossTX** [comment]
@aczechowski I'm claiming this issue for #MMS2019Docathon

**Comment by aczechowski** [comment]
Thanks @PhillyUrbs and @AdamGrossTX for the offer to help, although I don't see any pull requests for this. I'm fixing a bunch of issues today, so just going to do this one at the same time. I'll fix the examples (there's really not much to be done with this cmdlet except rename and add a description) and update the parameter descriptions. If you have any better examples with this cmdlet, please submit a pull request! (And @PhillyUrbs if you need help with that process, please let me know, happy to help!)

This issue will auto-close when my change merges, and then will go live with the next daily publishing process at ~4 PM Pacific
