### ISSUE TITLE
Inaccurate Examples

### ISSUE THREAD

**Issue by PhillyUrbs** [MicrosoftDocs/sccm-docs-powershell-ref#32]
The example used for this cmdlet uses parameters that are no longer supported.
-SecurityScopeAction and -SecurityScopeName

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7c386686-12f3-c7d3-8e0a-f0739978c4e3
* Version Independent ID: f278e68b-aa25-9ca2-e278-75a55c8931da
* Content: [Set-CMSite (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmsite?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMSite.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMSite.md)

**Comment by aczechowski** [comment]
Thanks @PhillyUrbs for the feedback. We unfortunately have a large backlog of work for the PowerShell & SDK content, but are looking at ways to improve it in the future. If you'd like to submit a change for this issue, see [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by AdamGrossTX** [comment]
@aczechowski I'm claiming this issue for #MMS2019Docathon

**Comment by aczechowski** [comment]
I just revised this article, fixing the description (which was way off!), the examples, and many of the parameter descriptions. The changes will publish live soon with the 2006 content release.
