### ISSUE TITLE
Add-CMSoftwareUpdatePoint -UseProxy $true -UseProxyForAutoDeploymentRule $true -> results in: "WSUS Control Manager failed to configure proxy settings on WSUS Server"

### ISSUE THREAD

**Issue by woerndlit** [MicrosoftDocs/sccm-docs-powershell-ref#33]
When using the -UseProxy and -UseProxyForAutoDeploymentRule with value $true, the following logs indicate an error:

SMS_WSUS_CONTROL_MANAGER: WSUS Control Manager failed to configure proxy settings on WSUS Server <servername>

WSUSCtrl.log: Microsoft.UpdateServices.Administration.WsusInvalidDataException: The address of the proxy server cannot be empty.~~   at Microsoft.UpdateServices.Internal.BaseApi.UpdateServerConfiguration.Validate()~~   at Microsoft.UpdateServices.Internal.BaseApi.UpdateServerConfiguration.Save(Boolean detectConfigChange)~~   at Microsoft.SystemsManagementServer.WSUS.WSUSServer.SetProxySettings(Boolean UseProxy, String ProxyName, Int32 ProxyServerPort, Boolean AnonymousProxyAccess, String ProxyUserName, String ProxyUserDomain, String ProxyUserPassword, Boolean AllowProxyCredentialsOverNonSsl)

If the wizard is used, proxy information is already filled from Site system properties and the issue is not present.

Did I miss something or is the cmdlet actually broken?

kind regards,
Tobias

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 21e97903-6768-38e3-b271-629a2ca083e8
* Version Independent ID: aad4ea04-f1f9-c3f1-a8b2-de4412c031d3
* Content: [Add-CMSoftwareUpdatePoint (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmsoftwareupdatepoint?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMSoftwareUpdatePoint.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMSoftwareUpdatePoint.md)

**Comment by aczechowski** [comment]
Thanks @woerndlit for taking the time to share this with the Configuration Manager documentation team. I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.

I'm closing this issue as there's nothing actionable for docs at this time.
