### ISSUE TITLE
-DeviceName parameter in example is not present in documentation

### ISSUE THREAD

**Issue by Christoph2020** [MicrosoftDocs/sccm-docs-powershell-ref#34]
Example 1:
Remove-CMDevice -DeviceName "WIN10-86-33"

Should the -Name Parameter be used instead?
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 570b70ac-79d6-e731-5173-72cfa493ace2
* Version Independent ID: ee17fd78-27d9-5691-4c1b-e46ea17bfa1e
* Content: [Remove-CMDevice (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmdevice?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMDevice.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMDevice.md)

**Comment by aczechowski** [comment]
Thanks @Christoph2020 for the feedback. If you look at the properties of the -Name parameter, DeviceName is an alias, so either will work. I'm closing this issue.

**Comment by DomDupuis** [comment]
I also got problems with this parameter (-name or -devicename),  to get the job done I use this:
Get-CMDevice -Name "COMPUTER_NAME" | Remove-CMDevice
