### ISSUE TITLE
-AppCategory and -UserCategory have been deprecated as of 1802

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/sccm-docs-powershell-ref#50]
-AppCategory and -UserCategory have been deprecated as of 1802, their replacements require getting the category first using Get-CMCategory and then feeding that result into the Set-CMApplication -AddAppCategory, -AddUserCategory, -RemoveAppCategory, -RemoveUserCategory, -CleanAppCategory, and -CleanUserCategory

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3ddb4b-ac44-1875-6e0b-3c14080da74f
* Version Independent ID: 4ac02258-93b5-baba-2cd5-3519e1210708
* Content: [Set-CMApplication (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmapplication?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMApplication.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMApplication.md)

**Comment by aczechowski** [comment]
Due to some weirdness with our repos over the past year, the changes from your PR weren't published. :( I duplicated them in the latest private version, which will publish soon with the 2006 content release. (And I'll be fixing the repo in the near future so that public contributions work again.)
