### ISSUE TITLE
Empty Example

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/sccm-docs-powershell-ref#60]
The example on this page is empty.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7b85c797-a7c2-3615-7a96-f1746b8fdd7e
* Version Independent ID: 757f7783-738c-2541-c0bc-030ea20f1337
* Content: [Start-CMObjectTracking (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/ConfigurationManager/Start-CMObjectTracking?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Start-CMObjectTracking.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Start-CMObjectTracking.md)

**Comment by aczechowski** [comment]
Hi @ChrisKibble, yep, a known issue throughout this content set. The automated tool we use to generate the content leaves those placeholders. I'm working to fill in some of it, but we honestly don't have the resources to address all of it right away. Community contributions to this repo are currently on hold while I fix some problems. Once that's done, then I'm hoping the community can help fill in some of these gaps. So for now, I'm closing this issue (along with your other similar issues)
