### ISSUE TITLE
Spelling mistake: Set-CMWinodwsFirewallPolicy

### ISSUE THREAD

**Issue by sam1310** [MicrosoftDocs/sccm-docs-powershell-ref#70]
Should be `Set-CMWindowsFirewallPolicy` instead of `Set-CMWinodwsFirewallPolicy`

https://docs.microsoft.com/en-us/powershell/sccm/1902-release-notes?view=sccm-ps#set-cmwinodwsfirewallpolicy
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9d13eab7-0416-6ec0-7b5e-591cc0c02e1f
* Version Independent ID: 8cfee86a-b643-45d0-8dc2-6261eaf681a0
* Content: [Version 1902 release notes - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/1902-release-notes?view=sccm-ps#feedback)
* Content Source: [docs-conceptual/1902-release-notes.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/1902-release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @sam1310 for the feedback. Do you want to submit a change for this issue? See [How to contribute](https://docs.microsoft.com/sccm/core/understand/use-docs#bkmk_contribute).

**Comment by aczechowski** [comment]
Thanks @sam1310 for the feedback. I fixed this string. The change will publish live soon with the 2006 content release.
