### ISSUE TITLE
"No Deployment Package" plans?

### ISSUE THREAD

**Issue by russrimm** [MicrosoftDocs/sccm-docs-powershell-ref#74]
Aware of any plans to add the "No Deployment Package" ADR option added to 1806 to this cmdlet or the New-CMAutoDeploymentRuleDeployment cmdlet?  If not i'll submit a uservoice for it.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a909f32d-5808-1dfc-f835-95fb8b260c54
* Version Independent ID: 9b1587a0-72ba-a5c6-3404-ac26b0797ed9
* Content: [New-CMSoftwareUpdateAutoDeploymentRule (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmsoftwareupdateautodeploymentrule?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMSoftwareUpdateAutoDeploymentRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMSoftwareUpdateAutoDeploymentRule.md)

**Comment by aczechowski** [comment]
Hi @russrimm, looks like this was added with 1906: https://docs.microsoft.com/en-us/powershell/sccm/1906-release-notes?view=sccm-ps#new-cmautodeploymentruledeployment

This content is mostly auto generated from what's in the module, but what's currently published is out of date (1902). I have a pending update to bring it up to the latest version.
