### ISSUE TITLE
No Example Shown

### ISSUE THREAD

**Issue by NathanTheGr8** [MicrosoftDocs/sccm-docs-powershell-ref#75]
Under Example 1 it just shows
PS C:\&gt;

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: af71c164-9664-59eb-9c2a-d165a04fd361
* Version Independent ID: 43e5c0d7-3b78-f3ec-8367-1cf48a8fbcc7
* Content: [Remove-CMPackageDeployment (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/remove-cmpackagedeployment?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Remove-CMPackageDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Remove-CMPackageDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mumian
* Microsoft Alias: **jgao**

**Comment by aczechowski** [comment]
Closing this issue as @ChrisKibble submitted a change to the article to add some actual examples. The change should publish live tomorrow.
