### ISSUE TITLE
Documentation is still in complete.

### ISSUE THREAD

**Issue by jordanmills** [MicrosoftDocs/sccm-docs-powershell-ref#78]
The sole example is... not.  Half the parameters have no description.  WTF is -value supposed to do, for example?  

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: de5f20a9-fac3-eea4-6974-b006632f6547
* Version Independent ID: f91bcec0-a21c-b8a7-d139-98dc02032f96
* Content: [New-CMDetectionClauseWindowsInstaller (ConfigurationManager)](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmdetectionclausewindowsinstaller?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/New-CMDetectionClauseWindowsInstaller.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMDetectionClauseWindowsInstaller.md)

**Comment by aczechowski** [comment]
The [Microsoft Open Source Code of Conduct](https://opensource.microsoft.com/codeofconduct/), which outlines the expectations for community interactions in and around docs.microsoft.com, is designed to help "provide a welcoming and inspiring community for all." The content of this issue appears to be out of sync with the code of conduct, so I'm closing it.

The PowerShell docs are auto-generated from the ConfigMgr module. We have limited resources to maintain the over 1100 cmdlet articles for this module (along with the 3200 articles in ConfigMgr core docs). We rely on community support from members like you to assist. If you have a sample example to share for this cmdlet, you can either share that via this feedback system, or submit an edit to the article to contribute your example. For more information, see [How to use the Configuration Manager docs](https://docs.microsoft.com/mem/configmgr/core/understand/use-docs).
