### ISSUE TITLE
Can the Output be a hyperlink to the object?

### ISSUE THREAD

**Issue by anwarmahmood1** [MicrosoftDocs/sccm-docs-powershell-ref#87]
https://docs.microsoft.com/en-us/sccm/develop/reference/apps/sms_deploymentsummary-server-wmi-class

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9c313f53-3eb5-49b0-4fe0-2fbae6c82dd7
* Version Independent ID: 19792b16-ab7c-de59-12c0-6db286ae67fa
* Content: [Get-CMApplicationDeployment - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmapplicationdeployment?view=sccm-ps#iresultobjectsms_deploymentsummary)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMApplicationDeployment.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMApplicationDeployment.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by anwarmahmood1** [comment]
The OUTPUTS formatting isn't ideal; it looks like only one type - IResultObject[]#SMS_DeploymentSummary - could be output.  In fact, I am guessing there are multiple types that could be output; in my experience, I am getting "IResultObject#SMS_ApplicationAssignment" back.

**Comment by aczechowski** [comment]
Thanks @anwarmahmood1 for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
