### ISSUE TITLE
Document flag for Optimized image servicing 

### ISSUE THREAD

**Issue by elang-bmrn** [MicrosoftDocs/sccm-docs-powershell-ref#89]
Can you please update this documentation to include the optimized image servicing feature that was introduced in SCCM 1902:

https://docs.microsoft.com/en-us/sccm/osd/get-started/manage-operating-system-images#bkmk_resetbase

The new switch is "-RemoveSupersededUpdates".

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 62851d2f-66d1-1710-d085-b4171b52890e
* Version Independent ID: 47f53a3d-2394-5781-c918-c692927615a0
* Content: [New-CMOperatingSystemImageUpdateSchedule - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/new-cmoperatingsystemimageupdateschedule?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/New-CMOperatingSystemImageUpdateSchedule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/New-CMOperatingSystemImageUpdateSchedule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by elang-bmrn** [comment]
Does this command even work? Copying the examples paramaters and extending, it seems like the output of the SUG command doesn't match the input required by the SoftwareUpdate parameter:

PS NA1:\> $images = get-cmoperatingsystemimage -Name 'Windows 10 Enterprise N'
>>
>> $corp_win10_sug = Get-CMSoftwareUpdateGroup -Name "2019-06-WorkstationSecurityUpdates"
>>
>> $images | ForEach-Object -Process {
>> ^I$image = $_
>> ^I
>> ^I$imageName = $image.name
>> ^I$sugName = $corp_win10_sug.LocalizedDisplayName
>>
>> ^Iwrite-output "Patching ${imageName} with ${sugName}"
>>
>> ^I$osiUpdateSchedule = $corp_win10_sug | `
>> ^I^INew-CMOperatingSystemImageUpdateSchedule `
>> ^I^I-Name $image.Name `
>> ^I^I-SoftwareUpdate $corp_win10_sug `
>> ^I^I-RemoveSupersededUpdates $true `
>> ^I^I-UpdateDistributionPoint $true `
>> ^I^I-RunNow `
>> ^I^I-ContinueOnError $true
>> ^IWrite-Output $osiUpdateSchedule
>> ^I}
Patching Windows 10 Enterprise N with 2019-06-WorkstationSecurityUpdates
New-CMOperatingSystemImageUpdateSchedule : Cannot bind argument to parameter 'SoftwareUpdate', because PSTypeNames of
the argument do not match the PSTypeName required by the parameter: IResultObject#SMS_SoftwareUpdate.
At line:16 char:19
+         -SoftwareUpdate $corp_win10_sug `
+                         ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-CMOperatingSystemImageUpdateSchedule], ParameterBindingArgumen
   tTransformationException
    + FullyQualifiedErrorId : MismatchedPSTypeName,Microsoft.ConfigurationManagement.Cmdlets.Osd.Commands.NewOperating
   SystemImageUpdateScheduleCommand

**Comment by aczechowski** [comment]
Thanks @elang-bmrn for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is as of version 1902. I have a pending update to bring it up to the latest version. The parameter you mention is now listed.

I’m sorry that you’re having problems, and I want to make sure it gets to the right people that can help. There are a couple of options available to provide the best level of support for this:
- Post on [Configuration Manager forums](https://social.technet.microsoft.com/Forums/en-US/home?category=ConfigMgrCB). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful.
- Use [Microsoft Support](https://aka.ms/cmcbsupport) to search for the issue, or open a case with professional support.
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager.
I'm closing this issue as there's nothing actionable for docs at this time.
