### ISSUE TITLE
missing AddAppCategory in docu

### ISSUE THREAD

**Issue by lumirjasny** [MicrosoftDocs/sccm-docs-powershell-ref#90]
Hello,
can you please check the docu, can not find the AddAppCategory,AddUserCategory ... parameter in https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmapplication?view=sccm-ps

many thanks
Lumir

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3ddb4b-ac44-1875-6e0b-3c14080da74f
* Version Independent ID: 4ac02258-93b5-baba-2cd5-3519e1210708
* Content: [Set-CMApplication - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/set-cmapplication?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Set-CMApplication.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Set-CMApplication.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @lumirjasny for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
