### ISSUE TITLE
Missing reference to UninstallContentLocation parameter.

### ISSUE THREAD

**Issue by ChrisKibble** [MicrosoftDocs/sccm-docs-powershell-ref#91]
Missing reference to UninstallContentLocation parameter.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9ec6f7db-a33c-ea9a-90d6-31261e8e28e2
* Version Independent ID: 4ecd32f7-c8e7-a810-728c-9ad1c659af2a
* Content: [Add-CMMsiDeploymentType - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/add-cmmsideploymenttype?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Add-CMMsiDeploymentType.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Add-CMMsiDeploymentType.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @ChrisKibble for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
