### ISSUE TITLE
Documentation on New Cmdlets

### ISSUE THREAD

**Issue by pfurches** [MicrosoftDocs/sccm-docs-powershell-ref#93]
I would love to see any documentation on the new cmdlets, especially New-CMRequirementRuleOUValue. I have been waiting YEARS for this one!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 83b95889-e52a-5cc6-eebf-630d9abb3522
* Version Independent ID: 73e4b737-e9f9-27ee-6ee5-0ad0ef1afddd
* Content: [Version 1810 release notes - Configuration Manager](https://docs.microsoft.com/en-us/powershell/sccm/1810-release-notes?view=sccm-ps#feedback)
* Content Source: [docs-conceptual/1810-release-notes.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/docs-conceptual/1810-release-notes.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @pfurches for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
