### ISSUE TITLE
Link to previous version

### ISSUE THREAD

**Issue by gbeaudoin78** [MicrosoftDocs/sccm-docs-powershell-ref#97]
The link Introduction to Collections in Configuration Manager (link is http://go.microsoft.com/fwlink/p/?LinkID=259433) point to a previous version documentation. Please update the link.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d8a45367-1771-6f86-1cfa-8fbd62837ae4
* Version Independent ID: 0a3ba2c4-2bd5-9659-7243-39d206b02871
* Content: [Get-CMDeviceCollectionQueryMembershipRule - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/get-cmdevicecollectionquerymembershiprule?view=sccm-ps#feedback)
* Content Source: [sccm-ps/ConfigurationManager/Get-CMDeviceCollectionQueryMembershipRule.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Get-CMDeviceCollectionQueryMembershipRule.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @gbeaudoin78 for the feedback. We had a lot of old and crusty links in this doc set. I just replaced all old fwlinks and previous-version references, including this one. The changes will publish live soon with the 2006 content release.
