### ISSUE TITLE
-NotificationType deprecated at 1810

### ISSUE THREAD

**Issue by BritV8** [MicrosoftDocs/sccm-docs-powershell-ref#98]
When using -NotificationType 
WARNING: The parameter 'NotificationType' has been deprecated and may be removed in a future release. The parameter 'ActionType' may be used as a replacement

suggest documentation changes to use the -ActionType
Aslo this parameter has far more options than -NotificationType

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a8723bff-f2e7-1ead-7349-315b5d6c0f3b
* Version Independent ID: c82275d1-dcd4-4be1-8031-dd91f38b53a7
* Content: [Invoke-CMClientNotification - Configuration Manager](https://docs.microsoft.com/en-us/powershell/module/configurationmanager/invoke-cmclientnotification?view=sccm-ps)
* Content Source: [sccm-ps/ConfigurationManager/Invoke-CMClientNotification.md](https://github.com/MicrosoftDocs/sccm-docs-powershell-ref/blob/master/sccm-ps/ConfigurationManager/Invoke-CMClientNotification.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @aczechowski
* Microsoft Alias: **aaroncz**

**Comment by aczechowski** [comment]
Thanks @BritV8 for the feedback. This content is mostly auto generated from what's in the module, but what's currently published is out of date. I have a pending update to bring it up to the latest version.
